UPDATE TDACM00080 SET COL_HNM = '3D OutdoorToIndoor분석 Coverage RSRP Limited Value' WHERE TAB_NM = 'NRSYSTEM' AND COL_ID = 38; --RELATED_ANALYSIS_COVLIMITRSRP
UPDATE TDACM00080 SET COL_HNM = '3D OutdoorToIndoor분석 Coverage RSRP Limited Value' WHERE TAB_NM = 'SCENARIO' AND COL_ID = 54; --RELATED_ANALYSIS_COVLIMITRSRP
COMMIT;