SELECT 'UPDATE TDACM00080 SET COL_HNM = ''3D OutdoorToIndoor분석 Coverage RSRP Limited Value'''||' WHERE TAB_NM = '''||TAB_NM||''' AND COL_ID = '||COL_ID||'; --'||COL_NM
FROM TDACM00080
WHERE JDBC_NM = 'EOS_DEV'
--AND LENGTH(IFNULL(TRIM(COL_HNM),'')) = 0
AND COL_NM = 'RELATED_ANALYSIS_COVLIMITRSRP'
UNION ALL 
SELECT 'COMMIT;' 

--CREATE TABLE TDACM00082 AS SELECT * FROM TDACM00080
--SELECT * FROM TDACM00082