nLang={l:{receipt_date:"받은날짜 :",save_date:"저장날짜 :",send_date:"보낸날짜:",receipt_send_date:"받은/보낸날짜:",date:"날짜:",
title:"메일 제목:",preview:"미리보기",preview_mail:"메일 내용 미리보기",open_preview_mail_layer:"메일 내용 미리보기 레이어 열림",
view_popup:"새 창으로 메일 보기",move_page_list:"메일 목록 페이지 이동",move_page_num:"이동 페이지",do_move_page:"페이지로 이동",
totalPage:"목록 전체 페이지 수",current_page:"현재 페이지",move_page:"{PageNum}페이지로 이동 중...",move_mail:"{FolderName}(으)로 이동했습니다.",
move_mail_undo:"{FolderName}(으)로 이동했습니다.<a href='javascript:;' class='_c1(mlCore|cancelDeleteMoveMailFromNoti)'>실행취소</a>",
cannot_move_temp_mail:"임시보관함 메일은 다른 메일함으로 이동할 수 없습니다.",nomail:"메일함에 메일이 없습니다.",no_search_result:"검색 결과가 없습니다.",
no_address:"주소없음",no_title:"(제목 없음)",view_header:"헤더 보기",view_mime:"원문 전체보기",select_mail:"메일 선택",order_by_criteria:"기준으로 목록 정렬",
ordered_by_criteria:"기준으로 목록 정렬됨",view_type_conversation:"대화형 보기",view_type_time:"시간순 보기",view_type_sender:"보낸사람 묶어보기",
display_type_list:"메일 목록만 보기",display_type_vertical:"상하 분할로 보기",display_type_horizontal:"좌우 분할로 보기",
view_sender_address:"보낸주소 보기",hide_sender_address:"보낸주소 감추기",toggle_receiver_view:"받는사람 모두 보기/접기",delete_mail:"휴지통의 메일을 지우면 지워진 메일들은 복구할 수 없습니다.\n\n메일을 삭제하시겠습니까?",
assign_spam_mail:"메일을 스팸으로 분류하였습니다.",delete_spam_mail:"스팸메일을 지우면 지워진 메일들은 복구할 수 없습니다.\n\n스팸메일을 삭제하시겠습니까?",
delete_mark_mail:"중요 메일입니다.\n\n삭제하시겠습니까?",delete_include_mark_mail:"중요 메일 포함되어 있습니다.\n\n삭제하시겠습니까?",deleted_mail_permanently:"메일을 영구삭제 했습니다.",
moved_mail_trash:"메일을 휴지통으로 이동했습니다.",moved_mail_trash_undo:"메일을 휴지통으로 이동했습니다. <a href='javascript:;' class='_c1(mlCore|cancelDeleteMoveMailFromNoti)'>실행취소</a>",
moved_mail_trash_undo_delete30:"메일을 휴지통으로 이동하며, 30일 보관 후 영구 삭제됩니다. <a href='javascript:;' class='_c1(mlCore|cancelDeleteMoveMailFromNoti)'>실행취소</a><a href='javascript:;' class='_c1(mlCore|optionConfirmFromNoti)'>설정확인</a>",
moved_mail_spam:"스팸메일함으로 이동했습니다.",move_inbox_add_receive_list:"선택한 메일을 받은메일함으로 이동하고, 메일주소를 수신허용 목록에 추가하시겠습니까?",
cancel_spam:"스팸해제",assign_spam:"스팸신고",delete_conversation:"모든 대화 메일을 삭제합니다.",confirm_add_reject:"보낸사람의 주소가 [수신차단목록]에 추가되어\n앞으로 이사람이 보낸 메일은 모두 차단되며, 차단 메시지가 발송자에게 전달됩니다.\n[수신차단 목록]에 추가하시려면 [확인]을 선택해 주세요.",
trash_notice_msg:"삭제메일은 {trashPeriod}일 후 영구 삭제됩니다. <a href='javascript:;' class='_c1(mlCore|optionConfirmFromNoti)'>설정확인</a>",
read_reserve_mail:"읽는 시간 지정 메일",reserve_mail:"예약메일",suspend_mail:"발송대기메일",calendar_mail:"캘린더 메일",approve_mail:"메일 승인",
send_mail:"보낸메일",text_mail:"텍스트메일",have_attach:"첨부파일 있음",have_attach_mail:"첨부파일있는 메일",npay_mail:"네이버페이 메일",
nsign_mail:"네이버Sign 메일",forward_read_mail:"전달한 읽은 메일",forward_no_read_mail:"전달한 읽지 않은 메일",reply_read_mail:"답장한 읽은 메일",
reply_no_read_mail:"답장한 읽지 않은 메일",count_receiver:"명의 받는이",during_receiver:"명 중 ",count_read_receiver:"명 읽음",
read:"읽음",unread:"안읽음",unread_2:"읽지않음",all_read:"모두읽음",part_unread:"일부안읽음",all_unread:"모두안읽음",before_send:"발송전",
sending:"발송중",send_success:"발송성공",send_fail:"발송실패",cancel_send:"발송취소",cancelled_sending:"발송취소",do_cancel_send:"발송취소하기",
cancel_reserve:"예약취소",cancelled_reservation:"예약취소",block_receive:"수신차단",cannot_confirm:"확인불가",exceed_quota:"용량초과",
cancel_fail:"취소실패",more_important:"중요도 높음",preview_in_web:"웹으로 미리보기",tome_mail:"내가 수신인에 포함된 메일",read_all:"전체 읽음",
unread_all:"전체 안읽음",filter:"필터",sort:"정렬",view_detail:"자세히 보기",read_receiver_count:"{ReadCount}/{ReceiverCount}명 읽음",
no_read_mail_in_receipt:"수신확인 목록에 '읽음' 상태의 메일이 없습니다.",no_unread_mail_in_receipt:"수신확인 목록에 '읽지않음' 상태의 메일이 없습니다.",
no_mail_in_receipt:"수신확인 목록에 메일이 없습니다.",no_email_address:"(받는이없음)",no_add_address:"추가할 주소가 없습니다.",set_important_address:"VIP주소로 표시하기",
clear_important_address:"VIP주소로 표시됨, VIP주소 해제하기",no_sender_receiver_address:"보낸/받는사람 주소가 존재하지 않습니다.",
autosorting_noti:"자동 분류 기능으로 손쉽고 편리하게 메일을 분류하고 관리해보세요.",highlight_reply:"내가 보낸 메일의 답장은 목록에서 강조 표시됩니다.",
highlight_frequently_address:"중요연락처로부터 온 메일은 목록에서 강조 표시됩니다.",highlight_appointment:"약속 메일은 목록에서 강조 표시됩니다.",
highlight_important:"중요한 메일을 놓치지 않도록 메일 강조 표시를 설정해 보세요.",cancel_reserved_mail:"본 메일의 예약발송을 취소하시겠습니까?",
cancel_delivery_mail:"본 메일의 발송을 취소하시겠습니까?",cancel_retrieve_mail:"발송을 취소하면 내부 수신자의 메일함에서 메일이 삭제됩니다.\n이 메일의 발송을 취소하시겠습니까?",
cancel_retrieve_mail_naver:"발송을 취소하면 네이버 수신자의 메일함에서 메일이 삭제됩니다.\n이 메일의 발송을 취소하시겠습니까?",cancel_delivery_mail_rcpt:"메일을 수정하기 전에 발송을 취소하셔야 합니다.\n이 메일의 발송을 취소하시겠습니까?",
cancel_reserve_mail_rcpt:"메일을 수정하기 전에 예약발송을 취소하셔야 합니다.\n이 메일의 예약발송을 취소하시겠습니까?",cannot_delete_reserved_mail:"발송 예약된 메일은 삭제하셔도 예약 취소되지 않습니다.\n예약 취소를 원하실 경우 수신확인 페이지에서 [취소]를 눌러 주세요.",
cannot_delete_delayed_mail:"발송 대기 상태의 메일은 삭제하셔도 발송 취소되지 않습니다.\n발송 취소를 원하실 경우 수신확인 페이지에서 [취소]를 눌러 주세요.",
cannot_delete_reserved_mail_rcpt:"발송 예약된 메일은 리스트에서 삭제되지 않습니다.\n예약 취소를 원하실 경우 각 메일에서 [취소]를 눌러 주세요.",cannot_delete_delayed_mail_rcpt:"발송 대기 상태의 메일은 리스트에서 삭제되지 않습니다.\n발송 취소를 원하실 경우 각 메일에서 [취소]를 눌러 주세요",
refer_mail_option:"다음 설정을 통하여 편리하게 메일을 이용해 보세요!",refer_divide_mode:"분할모드 첫화면 첫번째 메일 자동 보기 설정을 할 수 있습니다.",
refer_mail_action:"메일삭제/이동 후 자동으로 다음/이전 메일로 이동할 수 있습니다.",go_option:"환경설정 보기",security_secret:"기밀",security_in_house:"대외비",
security_no_delivery:"이 메일은 전달을 할 수 없습니다.",security_include_no_delivery:"전달이 불가능한 보안메일이 포함 되어 있으니 제외하고 다시 시도 하시기 바랍니다.",
infolder:"에 분류됨",works_tag:"LINE WORKS 계정으로 온 메일",no_selected_sent_mail:"선택한 메일에는 보낸 메일이 없습니다.",confirm_include_sent_mail:"선택하신 메일 중 보낸메일만 보낸메일함으로 이동합니다.",
loading_list:"목록을 불러오고 있습니다.",prev_list:"이전 목록",next_list:"다음 목록",disable_save_mail_over_count:"한번에 80개 메일 까지만 PC에 저장이 가능합니다.",
disable_report_mail_over_count:"한번에 80개 메일 까지만 스팸 신고가 가능합니다.",disable_save_contact_over_count:"한번에 80개 까지만 주소록 저장이 가능합니다.",
disable_forward_mail_over_count:"한번에 80개 메일 까지만 전달 가능합니다.",disable_keep_move_mail_over_count:"계속 이동은 최대 80개까지만 가능합니다.",
disable_arrange_mail_over_count:"정리할 메일은 최대 10개까지 선택할 수 있습니다.",disable_reject_mail_over_count:"한번에 80개 메일 까지만 수신 차단 가능합니다.",
filter_limit_10_address:"계속 이동은 중복되지 않은 메일 주소를 한 번에 10개까지만 설정할 수 있습니다. ",send_web_message:"메시지보내기",search_mail_from:"보낸 사람으로 검색하기",
search_mail_to:"받는 사람으로 검색하기",add_contact:"주소록에 추가하기",emphasize_send_mail:"보낸 메일 강조하기",classify_mailbox:"내 메일함으로 자동분류하기",
reject:"차단하기",delete_mail_from:"이 사람이 보낸 메일 모두 삭제",add_reject_list:"수신차단 목록에 추가하였습니다.",call_delete_mail:"삭제할 메일 수에 따라 다소 시간이 걸릴 수 있습니다.",
set_emphasize_mail:"보낸 메일 강조하기를 설정하였습니다.\n이후 수신되는 메일은 목록에서 색상 강조되어 표시 됩니다.",add_classify_rule:"자동분류 항목을 추가 하였습니다.",
confirm_delete_mail:"현재 메일함에서 이 사람이 보낸메일을 모두 휴지통으로 삭제합니다.",vip_saved_desc:"VIP로 지정되었습니다.",block_image_link:"이미지/링크 차단하기",
number_of_relative_mail:"{threadCount}<span class='blind'>개의 관련 메일있음</span>",number_of_relative_mail2:"{Number}<span class='blind'>개의 관련 메일있음</span>",
delete_from_delete_list:"메일 삭제 리스트에서 제거",show_employee_info:"구성원 정보 보기",show_bilateral:"이 사람과 주고받은 메일",
big_attach_file:"대용량 첨부파일",attach_bigfile_desc:"대용량 첨부 파일은 메일 읽기에서 확인이 가능합니다.",prev_attach_desc:"이전 첨부파일 보기",
next_attach_desc:"다음 첨부파일 보기",see_in_office_viewer:"오피스뷰어로 보기",all_file_delete_desc:"첨부파일이 삭제되었습니다.",
approve_authorize:"승인",approve_hold:"대기",approve_reject:"반려",receivetip_helplink_receive_naver:"https://help.naver.com/support/alias/mail/mail6.naver",
receivetip_helplink_cancel_naver:"https://help.naver.com/support/alias/mail/mail7.naver",receivetip_helplink_receive_nwe:"https://help.worksmobile.com/contents/contents.nhn?serviceNo=2&categoryNo=611",
receivetip_helplink_cancel_nwe:"https://help.worksmobile.com/contents/contents.nhn?serviceNo=2&categoryNo=610",
there_is_no_content:"메일 내용이 없습니다.",there_is_no_memo:"메모 내용이 없습니다.",unable_to_check:"확인불가",remind_scheduled:"리마인드 예정",
remind_complete:"리마인드 됨",remind_set_noti:"리마인드가 설정되었습니다.",remind_clear_noti:"리마인드 설정을 삭제했습니다.",remind_date:"리마인드 날짜: ",
remind_fail_draft:"임시보관함에 있는 메일은 리마인드 설정할 수 없습니다.",remind_fail_spam:"스팸메일함에 있는 메일은 리마인드 설정할 수 없습니다.",
remind_fail_trash:"휴지통에 있는 메일은 리마인드 설정할 수 없습니다.",remind_fail_reserve:"예약/대기 메일은 리마인드 설정할 수 없습니다.",fail_invalid_desc1:"임시보관함, 스팸메일함, 휴지통에 있는 메일과 예약/대기 메일은 리마인드 설정할 수 없습니다.",
fail_invalid_desc2:"이를 제외한 일반 메일만 리마인드 설정합니다.",cannot_clear_complete:"리마인드 예정인 메일만 리마인드 해제됩니다.",remind_fail_min_time:"리마인드는 최소 10분 후부터 설정 가능합니다.",
remind_fail_max_time:"리마인드는 최대 1년까지 설정 가능합니다.",remind_invalid_date:"유효하지 않는 날짜/시간 입니다.",remind_filter_time:"메일 수신 시간",
remind_self_edit:"직접입력",remind_after_hour:"{Val}시간 후",remind_no_day:"요일 지정 없음",remind_sunday:"일요일",remind_monday:"월요일",
remind_tuesday:"화요일",remind_wednesday:"수요일",remind_thursday:"목요일",remind_friday:"금요일",remind_saturday:"토요일",
filter_time:"날짜",eoo:""},f:{whole_mail_folder:"전체메일함",idomain_mail_folder:"네이버웍스 받은메일함",sent:"보낸메일함",
inbox:"받은메일함",trash:"휴지통",draft:"임시보관함",read_receipt:"수신확인",spam:"스팸메일함",tome:"내게쓴메일함",bill:"청구서",cafe:"카페",
sns:"SNS",shop:"프로모션",system:"기본메일함",custom:"내메일함",idomain:"도메인 메일",worksmail:"네이버Works 메일",all_for_title:"전체메일",
all_move_folder:"이동메일함 전체",smart_folder:"스마트메일함",new_folder:"새 메일함",no_folder:"메일함없음",rename_folder:"메일함 이름 수정",
no_read_mail:"안읽은 메일",add_childfolder:"하위 메일함 추가",cannot_be_in_child_folder:"자신의 하위 메일함으로 이동할 수 없습니다.",
cannot_be_in_system_folder:"시스템 폴더 하위로는 메일함을 생성할 수 없습니다.",depth_limit_5:"메일함은 5depth 까지만 만드실 수 있습니다.",
count_limit_1000:"메일함 갯수는 1000개를 초과할 수 없습니다.",length_limit_20:"메일함 이름은 20자까지 입력이 가능합니다.",length_limit_70:"메일함 이름은 70자까지 입력이 가능합니다.",
noname:"메일함 이름을 입력하세요.",noname_save_folder:"저장할 메일함 이름을 넣어주십시오.",already_exist:"이미 존재하는 메일함입니다.",no_parent_folder:"상위 메일함이 존재하지 않아 메일함을 만드실 수 없습니다.",
slash_limit_position:"'/'는 메일함의 처음이나 마지막에 올수 없습니다.",slash_limit_continuous:"'/'는 연속하여 사용할수 없습니다.",slash_limit_idomain:"도메인 메일함명에 특수기호 '/'를 입력할 수 없습니다.",
cannot_use_slash_foldername:"메일함 이름에 / 는 사용할 수 없습니다.",cannot_use_slash_foldername_2:"메일함(메모함) 이름에 /는 사용할 수 없습니다.",
nomail_to_backup:"백업할 메일이 없습니다.",fold_folder:"하위 메일함 열기/접기 토글",try_to_clear_trash:"휴지통을 비우시면 지워진 메일(중요메일 포함)들은 복구할 수 없습니다.\n대량의 메일을 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n휴지통을 비우시겠습니까?",
clear_folder_type_trash:"{Name} 비우기 시, 메일함에 있던 모든 메일(중요메일 포함)은 휴지통으로 이동합니다.\n대량의 메일을 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n메일함을 비우시겠습니까?",
clear_folder_type_delete:"{Name} 를 비우시면, 메일함에 있던 모든 메일(중요메일 포함)은 삭제되며 복구할 수 없습니다.\n대량의 메일을 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n메일함을 비우시겠습니까?",
clear_folder_receipt_noti:"수신확인을 비우시면 지워진 리스트들은 복구 할 수 없습니다.\n대량의 메일을 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n수신확인을 비우시겠습니까?",
clear_spam_folder:"스팸메일함을 비우면 지워진 메일(중요메일 포함)들은 복구할 수 없습니다.\n대량의 메일을 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n스팸메일을 삭제하시겠습니까?",
delete_folder_no_child_trash:"{Name} 삭제 시, 메일함에 있던 모든 메일(중요메일 포함)은 휴지통으로 이동합니다.\n대량의 메일을 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n메일함을 삭제하시겠습니까?",
delete_folder_no_child_delete:"{Name} 을 삭제하시면, 메일함에 있던 모든 메일(중요메일 포함)은 삭제되며 복구할 수 없습니다.\n대량의 메일을 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n메일함을 삭제하시겠습니까?",
delete_folder_has_child_trash:"{Name} 삭제 시, 하위 메일함도 함께 삭제되며\n하위 메일함을 포함하여 메일함에 있던 모든 메일(중요메일 포함)은 휴지통으로 이동합니다.\n대량의 메일을 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n메일함을 삭제하시겠습니까?",
delete_folder_has_child_delete:"{Name} 을 삭제하시면, 하위 메일함도 함께 삭제되며\n하위 메일함을 포함하여 메일함에 있던 모든 메일(중요메일 포함)이 삭제되어 복구할 수 없습니다.\n대량의 메일을 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n메일함을 삭제하시겠습니까?",
duplicate_folder_name:"같은 이름의 메일함이 이미 있습니다. 내 메일함 중 {FolderName} 메일함을 다른 이름으로 변경한 후에 이름 초기화를 해 주세요.",
confirm_delete_all:"현재 메일함에서 안읽은 메일(중요메일 포함)를 모두 삭제하시겠습니까?",confirm_read_all:"현재 메일함에서 안읽은 메일(중요메일 포함)을 모두 읽음으로 표시하시겠습니까?",
confirm_read_all_memo:"현재 메모함에서 안읽은 메모(중요메모 포함)를 모두 읽음으로 표시하시겠습니까?",folder_read_all:"메일함을 모두 읽음으로 표시하였습니다.",
mybox_unfold:"내 메일함 펼치기",mybox_fold:"내 메일함 접기",vip_folder:"VIP 메일함",vip_folder_toggle:"VIP 메일함 접고/펴기 토글",
vip_select_to_vip:"VIP로 지정하기",vip_move_contact:"중요연락처 지정하기",read_all_folder:"{FolderName} 의 안 읽은 메일이 모두 읽음으로 표시됩니다.\n\n모두 읽음으로 표시하시겠습니까?",
moved_mail_trash:"삭제메일을 휴지통으로 이동했습니다.",to_view_lang:"외국어 메일 보기",to_view_origin:"원문 보기",eoo:"",smartmail_setting1:"선택한 메일은 ",
smartmail_setting2:"으로 이동되었습니다."},r:{popup_read_limit_5:"한번에 최대 5개까지의 메일을 새 창으로 열 수 있습니다.",no_prev_mail:"이전 메일이 없습니다.",
no_next_mail:"다음 메일이 없습니다.",go_top:"맨위로",view_all:"전체보기",end_read_mail:"메일 읽기 완료",popup_window:"새 창으로 메일 보기",
getting_mail_page:"메일 읽는 중 ...",confirm_retrieve_mail:"본 메일의 발송을 취소하시겠습니까?\n\n발송취소의 상세 내역은 수신확인 페이지에서 확인할 수 있습니다.",
confirm_delete_attach:"첨부파일을 삭제하시면 복구가 불가능합니다.\n첨부파일을 삭제하시겠습니까?",read_mail:"읽은 메일",not_read_mail:"읽지않은 메일",
not_read_count:"안읽은 메일 수",relative_mail:"주고받은 메일",add_address:"주소록에 추가",reject_address:"수신차단하기",send_date:"보낸날짜",
invite_event:"약속초대",preview_image:"이미지 미리보기",preview_attach_file_image:"첨부 파일 이미지 미리보기",preview_attach_image_list:"첨부 이미지 미리보기",
notice_reply_time:"{ReplyTime}에 이 메일에 답장을 보냈습니다.",notice_forward_time:"{ForwardTime}에 이 메일을 전달했습니다.",
locate_number_of_image:"<em>{ImageCount}개</em>의 이미지가 있습니다.",link_photoviewr:"사진 감상과 편집은 <strong>네이버 포토뷰어</strong>",
hide_more_info:"추가정보 감추기",show_more_info:"추가정보 보기",normal_attach_file:"일반 첨부파일",delete_attach_file:"첨부파일 삭제",
download_pc:"PC저장",download_all:"모두 저장",download_all_ndrive:"네이버클라우드에 저장",download_all_officedrive:"드라이브에 저장",
download_all_worksdrive:"드라이브에 저장",download_all_pc:"PC에 저장",download_original_file:"원본파일 저장",download_cured_file:"치료된 파일 저장",
auto_virus_check:"파일 저장 시 바이러스 검사 자동 수행",end_virus_check:"바이러스 검사 결과",detected_virus:"첨부파일에서 바이러스(악성코드)가 발견되었습니다.",
detected_virus_cured_file_list:"발견 된 바이러스와 치료 된 첨부파일 목록",virus_type:"진단명",cured_file:"치료된 첨부파일",check_engine:"검사 엔진",
check_engine_name:"McAfee 보안 솔루션",ndrive:"네이버클라우드",officedrive:"드라이브",warning_file_ncs:"외부에서 전달된 메일의 첨부파일에는 악성코드가 숨겨져 있을 가능성이 있습니다. 열람 전 메일발송자가 아는 사람인지, 본인이 받아야 하는 메일이 맞는지 확인해주시기 바랍니다.\n첨부파일 실행 후 이상 증상이 발견되면 사내보안담당자(dl_office_security@navercorp.com)에게 신고 바랍니다. 위 내용을 확인하였으며 현재 파일을 신뢰할 수 있다면 확인 버튼을 클릭하세요.",
warning_file_string:"[주의]</span> 이 메일의 첨부파일에는 악성코드가 숨겨져 있을 가능성이 있으므로 다운로드 시 주의하시기 바랍니다.",attach_withdraw:"대용량 첨부파일 회수",
attach_withdraw_desc1:"회수 이후, 수신자의 메일에서 첨부파일이 다운로드 되지 않습니다.",attach_withdraw_desc2:"첨부된 대용량 파일만 회수하시겠습니까?\n단, 메일은 회수되지 않으며, 수신자가 메일 내 첨부된 대용량 파일을 다운로드 할 수 없습니다.",
attach_withdraw_desc3:"보낸사람이 메일 발송 후, 대용량 첨부파일을 회수하여 파일을 다운로드 할 수 없습니다.",fake_mail_noti:"사칭메일 안내",fake_mail_noti_desc:'<span class="ico_caution">이 메일은 [{DOMAINSTRING}]을 통해 발송된 메일이 아닙니다.</span> 보낸 사람의 주소가 실제 발송 주소와 다를 수 있으니 주의하시기 바랍니다. <a href="javascript:;" class="normal_text _c1(myCore|showFakeNotiLayer|show)">자세히보기</a>',
fake_mail_noti_desc_no_sender:'<span class="ico_caution">이 메일은 NAVER에 존재하지 않는 계정에서 발송된 메일입니다.</span> 보낸 사람의 주소가 실제 발송 주소와 다를 수 있으니 주의하시기 바랍니다. <a href="javascript:;" class="normal_text _c1(myCore|showFakeNotiLayer|show)">자세히보기</a>',
fake_mail_noti_desc_suspicious_sender:'<span class="ico_caution">안전하지 않은 메일로 의심되니 발송자를 다시 확인해 주세요.</span> 본문의 링크를 클릭하거나 첨부파일 다운로드시 유의해 주세요.',
unuse_spam_link_image:"이 메일은 회원님께 피해를 줄 수 있는 이미지, 악성코드를 포함할 수 있어 링크를 제거하고, 이미지를 다운로드하지 않았습니다.",use_spam_link_image:"스팸 메일 이미지/링크를 표시하고 있습니다.",
show_link_image:"이미지/링크 표시하기",hide_link_image:"이미지/링크 숨기기",unuse_external_link_image:"보안 목적으로 메일 내용이 일부 표시되지 않습니다.",
trust_external_address:"{Address} 에서 보낸 메일은 항상 신뢰하기",schedule:"일정",send_accept_mail:"수락 메일을 발송했습니다.",
send_tentative_mail:"미정 메일을 발송했습니다.",send_reject_mail:"거절 메일을 발송했습니다.",confirm_accept_schedule:"<strong>초대를 수락하시면</strong> 보낸 사람의 연락처가 내 주소록에 추가되고, 앞으로는 이 사람이 보낸 초대 일정이 내 캘린더에 자동 등록됩니다.",
refer_accept_schedule1:"초대에 수락/미정으로 응답하시면 보낸 사람의 연락처가 내 주소록에 추가되고, 앞으로는 이 사람이 보낸 초대 일정이 내 캘린더에 자동 등록됩니다.",
refer_accept_schedule2:'주소록 등록 여부와 관계없이 모든 초대 일정을 내 캘린더에 자동 등록하고 싶다면, <a href="javascript:;" class="_c1(mrCore|openCalenderOptionPage) _stopDefault">[캘린더 > 환경설정]</a> 에서 초대받은 일정의 자동 등록 설정을 변경 가능합니다.',
cannot_idomain_use_auto_add_calendar:"개인 도메인 설정된 메일 주소에서는 외부 약속 초대 일정(.ics)을 <br>네이버 캘린더로 자동 추가하는 인터페이스를 지원하지 않습니다.",
cannot_accept_my_schedule:"본인이 초대한 약속 일정에는 응답하실 필요가 없습니다.",expire_reply:"이 회신 상태는 최신이 아닙니다. 참석자가 이 초대에 다른 응답을 했습니다.",
change_schedule:"이 약속 정보는 변경되었습니다. 최신 상태를 확인해 주세요.",cancel_schedule:"약속 마스터가 이 일정을 취소했습니다.",no_invitation:"이 약속 일정에 초대 받은 사용자가 아닙니다.",
reply_changed_schedule:"이 약속이 변경되어 응답할 필요가 없습니다. 변경된 약속 초대에 응답해 주세요.",schedule_from:"님께서 ",accept_schedule:"약속 초대에 <strong>수락</strong>으로 응답하셨습니다.",
reject_schedule:"약속 초대에 <strong>거절</strong>으로 응답하셨습니다.",tentative_schedule:"약속 초대에 <strong>미정</strong>으로 응답하셨습니다.",
new_accept_schedule:"{EmailLink}님께서 약속 초대에 <strong>수락</strong>으로 응답하셨습니다.",new_reject_schedule:"{EmailLink}님께서 약속 초대에 <strong>거절</strong>으로 응답하셨습니다.",
new_tentative_schedule:"{EmailLink}님께서 약속 초대에 <strong>미정</strong>으로 응답하셨습니다.",accept:"수락",tentative:"미정",
reject:"거절",schedule_time:"일시",pm:"오후",am:"오전",schedule_detail:"일정 자세히 보기",hour:"시간",minute:"분",noPreviousSchedule:"이전 일정 없음",
noNextSchedule:"이후 일정 없음",previousDay:"이전",allDay:"종일",reply_accept_not_invited:"이 일정에 초대받지 않은 {SenderLink}님이 일정을 전달받아 <b>{ReplyType}</b>으로 응답하셨습니다.",
cal_response_title_tentative:"이 초대에 미정으로 응답하시겠습니까?",cal_response_notice1_tentative:"약속 마스터에게 응답(미정) 알림이 발송되며,",
cal_response_notice2_tentative:"바쁨 상태로 변경됩니다.",cal_response_title_reject:"이 초대를 거절하시겠습니까?",cal_response_notice1_reject:"약속 마스터에게 응답(거절) 알림이 발송되며,",
cal_response_notice2_reject:"한가함 상태로 변경됩니다.",cal_response_title_repetitive_reject:"거절하시면 전체 반복 일정이 거절됩니다.",
cal_response_notice_repetitive_reject:"이 초대를 거절하시겠습니까?",security_after_delete:"삭제",security_no_resend:"재전송 금지",
more_view_reciever_toggle:"받는사람/참조 접기/펴기",save_file_ndrive_tooltip:"네이버클라우드 저장",save_file_ncsdrive_tooltip:"드라이브 저장",
save_file_drive_tooltip:"드라이브 저장",no_quickReply:"직접 입력한 빠른 답장이 없습니다",sticker:"스티커",select_quickReply:"빠른 답장 선택",
click_quickReply:"빠른 답장을 하시려면 여기를 클릭해 주세요.",respond:"답장하기",respond_all:"전체답장하기",confirm_quickReply1:"수신된 메일의 발신자에게만 메일을 발송합니다.",
confirm_quickReply2:"수신된 메일의 발신자 및 참조자 모두에게 메일을 발송합니다.",enter_quickReply:"빠른 답장 내용을 입력해 주세요",limit_quickReply:"빠른 답장 내용은 12,000bytes 이내로 입력해 주세요.",
max_quickReply:"빠른 답장은 최대 10개까지 만들 수 있습니다.",edit_quickReply:"빠른 답장 수정하기",make_quickReply:"빠른 답장 만들기",
delete_quick_msg:"선택된 빠른 답장을 삭제하시겠습니까?",cal_response_placeholder:"마스터에게 전할 메시지를 입력하세요. (최대 150자)",open_translate_popup:"새 창으로 번역하기",
korean:"한국어",japanese:"일본어",english:"영어",simplified_chinese:"중국어 간체",traditional_chinese:"중국어 번체",already_authorized:"이 메일은 승인되었습니다.",
enter_rejection:"반려 사유를 입력해주세요.",already_rejected:"이 메일은 반려되었습니다.",rejection_reason:"반려 사유",request_authorize:"메일 발송 승인 요청",
rejection_confirm:"확인",enter_rejection_optional:"* 반려 사유 입력은 선택사항 입니다.",approve_authorize:"승인",approve_reject:"반려",
eoo:"",add_event_to_calendar:"+ 캘린더에 일정 추가",publish_schedule_noti1:"수락/미정/거절 응답이 필요한 약속 일정이 아닙니다.",publish_schedule_noti2:"캘린더에 일정 추가하면 내 계정이 마스터인 상태로 새로운 일정이 등록됩니다."
},w:{write_mail:"메일쓰기",write_tome:"내게쓰기",hide_bcc:"숨은 참조 숨기기",show_bcc:"숨은 참조 보이기",calendar_invalid_format:"날짜 범위를 벗어났습니다. 다시 입력해 주세요.",
upload_fail:"첨부파일 업로드가 실패하였습니다.\n\n첨부파일 없이 메일을 보내겠습니까?",use_ndrive_send:"네이버클라우드에서 메일로 보내기 기능은 대용량 첨부 모드로 변경하셔야만 사용이 가능합니다.\n메일의 첨부 모드를 대용량첨부 모드로 변경하시겠습니까?",
use_normal_send:"일반첨부 모드로 전환하시면 대용량첨부 모드에서 \n 올린 파일들은 새로 첨부하셔야 하며, \n10MB 이상의 파일들은 첨부하실 수 없습니다.\n\n일반첨부 모드로 전환하시겠습니까?",
use_bigfile_send:"대용량첨부 모드로 전환하시겠습니까?",change_normal_attach:"일반첨부로 전환",change_bigfile_attach:"대용량첨부로 전환",
use_activex_only_ie:"IE이외의 브라우저에서는 ActiveX 모드로 전환할 수 없습니다.",install_activex_msg:"작성중인 내용이 사라질 수 있습니다. 계속하시겠습니까?",
select_only_img:"이미지 파일만 선택할 수 있습니다.",not_commend_bmp:"BMP 파일은 웹상에서 사용하기엔 적절한 이미지 포맷이 아닙니다.\n그래도 계속 하시겠습니까?",
select_img:"본문에 삽입할 이미지를 선택해주세요.",upload_fail2:"파일을 업로드할 수 없습니다.",upload_fail_vdi:"VDI에서는 파일을 첨부할 수 없습니다.",
upload_fail_zero_byte:"업로드에 실패하여 용량이 0 byte로 첨부된 파일이 있습니다. 파일첨부 목록에서 삭제 후 다시 첨부해 주세요.",cannot_upload_by_drive:"드라이브 파일 보내기는 HTML5 지원 브라우저에서만 가능합니다.\n첨부할 파일을 다시 선택해 주세요.",
invalid_sender_cellphone_num:"보내는 사람 휴대폰번호가 올바르지 않습니다.",type_only_num:"숫자만 입력하세요.",sending_mail:"메일 발송중입니다!",
send_mail_end:"메일발송 완료",save_temporary_folder:"임시보관함에 저장함. {Time}",go_inbox:"받은메일함가기",go_draft:"임시보관함으로 가기",
go_tome:"내게쓴메일함으로 가기",send_result_notice:"새로워진 주소록에서 <strong>그룹메일과 문자를 편리하게 보내보세요!</strong>",add_address_to_important:'<strong id="setImportantAddressMsgViewEmail">email</strong>을 주소록에 추가하였습니다.',
refer_frequent_address:"중요 연락처로 추가하시면 메일쓰기>자동완성 레이어에서 메일 주소를 쉽게 찾을 수 있습니다.",add_address_to_frequent:"{Address}을<br/>중요 연락처로 추가했습니다.",
add_frequent_address:"중요 연락처로 추가",add_to_group:"{FirstEmail} 외 {RecieverCount} 명을<br/>‘{GroupName}’에 추가하였습니다.",
add_group:"그룹추가",group_name:"그룹이름",group_name_limit_length_25:"그룹명은 최대 25자까지 입력할 수 있습니다.",confirm_exist_group:"기존그룹 확인",
all_address:"전체주소",frequent_address:"중요 연락처",recent_address:"최근 사용한 주소",blog_address:"블로그 이웃",find_address:"메일주소 찾기",
cannot_detect_address:"찾으시는 메일주소가 등록되어 있지 않습니다.",no_select_mail:"선택된 메일 주소가 없습니다.",no_used_recent_mail_address:"<em>최근 사용한 주소</em>가 없습니다.",
no_often_used_mail_address:"<em>중요 연락처</em>가 없습니다.",auto_save_often_used_mail_address:"<p>메일을 자주 보낸 메일주소가 중요 연락처로 자동보관됩니다.<br />중요 연락처의 자동 저장 조건은 주소록에서 설정할 수 있습니다.</p>",
common_address:"공용 주소록",cannot_delete_saved_address:"주소록에 저장된 주소는 삭제할 수 없습니다.",edit_fromname:"{Name}로 보내는 이름을 수정함",
type_fromname:"보내는이름이 지정되지 않았습니다.\n보내는이름을 입력해 주세요.",type_receiver_address:"받는사람이 지정되지 않았습니다.\n받는 사람 주소를 입력해 주세요.",
type_title_send_no_title:"제목이 지정되지 않았습니다. 제목 없이 메일을 보내시겠습니까?",limit_upload_size:"일반첨부는 메일 본문을 포함하여 최대 {FileSize}를 넘을 수 없습니다.",
limit_upload_image_size:"에디터 내 이미지 삽입은 일반 첨부를 포함하여\n최대 {size}를 넘을 수 없습니다.",limit_upload_image_count:"에디터 내 이미지 삽입은 최대 {count}개까지 선택 가능합니다.",
limit_upload_size_forward:"첨부파일이 발송 용량을 초과하여 제외되었습니다.\n파일 전달을 원하시면 로컬에 저장 후 대용량첨부 방식으로 다시 업로드해주세요.",
auto_save_receiver_address:"받는 사람 주소는 설정에 따라 주소록에 자동저장 됩니다.",confirm_send_appointment_mail:"지정한 약속에 [확인] 버튼을 누르지 않은 상태입니다.\n이 메일을 약속 메일로 보내시겠습니까?",
appointment_mail_due_limit_5:"예약메일은 최대 5년까지 설정 가능합니다.",appointment_time_late_invite_time:"예약시간이 캘린더 초대일정보다 늦습니다.\n\n초대일정 후에 메일이 발송되지 않도록 예약시간을 변경해 주세요.",
appointment_time_late_current_time:"예약시간은 현재시간보다 늦은 시간이어야 합니다.",cannot_use_dormancy_idomain:"개인 도메인 메일의 사용이 중단되어,\n네이버 메일 주소로 메일을 작성합니다.\n개인 도메인 메일 사용 중단에 대해서 궁금하신 것이 있으시면,\n네이버 메일 도움말을 참고하시거나, 고객센터에 문의해 주세요.",
cannot_use_special_char_fromname:"보내는이름에는 특수문자 '<' '>' '\\' '\"' 는 사용 하실 수 없습니다.",cannot_add_appointment_idomain:"개인 도메인 메일주소로 보내는 메일에는\n약속잡기를 추가할 수 없습니다.",
possible_reserve_send_time:"원하는 시간으로 발송 시간을 예약할 수 있습니다.",delete_appointment:"약속을 삭제하시겠습니까?",type_format_yy_mm_dd:"{format} 형태로 입력해 주십시오.",
change_sender_address:"발신 주소를 변경하시겠습니까?",send_reserve:"발송예약",select_std_time:"기준 시간 선택",change_normal_to_tome:"작성 내용 중 제목, 본문 내용만 유지되며, 다른 사람에게 보낼 수 없습니다.\n\n내게쓰기로 전환하시겠습니까?",
change_tome_to_normal:"받는 사람이 지정되어 내게 쓰기가 아닌 일반 쓰기로 전환됩니다.",alert_cannot_use_address_book_tome:"내게쓰기 모드에서는 주소록을 사용하실 수 없습니다.",
alert_leaving_write_page:"이 페이지를 벗어나면 마지막 저장 후 수정된 내용은 저장되지 않습니다.",cannot_support_under_ie6:"ie6 이하 브라우저에서는 지원하지 않는 기능입니다.",
cannot_support_iframe:"현재 사용하시는 브라우저는 IFRAME을 지원하지 않습니다.",clear_source_view:"소스보기 해제하고 사용해주세요.",over_address_count:"외부주소로는 {limit_address_count}개까지만 발송가능합니다.\n현재 추가된 외부 주소 : {current_address_count}개 / {limit_address_count}개",
include_exteranl_address:"주소에 외부계정이 포함되어 있습니다.\n기밀·대외비로 설정된 보안메일은 외부계정으로 발송하실 수 없습니다.",bcc_reply_all:"숨은 참조로 받은 메일입니다.\n이 메일에 대해 전체 답장을 하시겠습니까?",
alert_dl_to_address:"보내는 사람(From)을 메일링리스트 주소로 하여 발송하시겠습니까?\n메일링리스트 주소를 사용하여 메일 발송시,\n해당 메일링리스트에 포함된 구성원도 숨은 참조로 메일을 받게 됩니다.",
alert_dl_address_sending_with_schedule:"메일링 그룹(DL/ML) 계정으로 메일 발송 시에는 약속잡기를 설정할 수 없습니다.\n보내는 사람을 변경하거나 약속삭제 후 보내기 해주세요.",
type_capcha:"<em>스팸메일 발송 방지를 위한 문자를<br>입력해 주세요.</em>",invalid_capcha:"<em>입력된 문자가 올바르지 않습니다.<br>다시 입력해 주세요.</em>",
captcha_image:"이미지로 보기",captcha_sound:"음성으로 듣기",captcha_message_image:"문자/숫자를 보이는 순서대로 모두 입력 후 보내기를 눌러주세요.",
captcha_message_sound:"스피커를 통해 들리는 대로 입력해 주세요.",normal:"일반",bigfile:"대용량",change:"전환",unlimit:"제한없음",
days:"일간",normal_attach:"일반첨부",bigfile_attach:"대용량첨부",disable_attach_type:"첨부방식 전환불가",pause_upload:"업로드 중지",
status_wait:"대기 중",status_upload:"전송 중",status_pause:"일시 중지",upload_size1:"전송량",upload_size2:"전송 용량",
upload_status:"전송 상태",upload_time:"전송 시간",upload_speed:"전송 속도",upload_file:"전송 파일",upload_complete:"업로드 완료",
total_upload:"전체 전송",select_file:"을 선택",upload_complete2:"전송 완료",total_attach_alert:"일반 첨부는 본문을 포함하여 {AttachFileMaxSize} 이하, 대용량첨부는 {BigFileMaxCount}개까지 첨부 가능합니다.",
bigfile_attach_limit_count_oneday:"대용량첨부 사용은 일일 {BigFileMaxNumber}번만 가능합니다!",bigfile_attach_limit_count_onetime:"대용량첨부는 {BigFileMaxCount}개까지 가능합니다.",
bigfile_attach_limit_size:"대용량첨부는 {BigFileMaxSize} 미만까지 업로드 가능합니다.",bigfile_not_supported:"용량이 커서 바로 첨부되지 않습니다.\n메일 원문을 PC에 저장하신 후 파일 첨부해주세요.",
normal_attach_limit_count_100_onetime:"일반첨부는 100개까지 가능합니다.",normal_attach_limit_size:"일반첨부는 메일 본문을 포함하여 최대 {FileSize}를 넘을 수 없습니다.\n(지금까지 총 {TotalSize}추가)",
normal_attach_limit_size_10:"일반첨부 전체 파일 크기는 10.00MB를 넘을 수 없습니다.",cannot_upload_size_0:'"{FileName}" 파일은 크기가 0 byte입니다.',
cannot_upload_folder:"폴더는 첨부하실 수 없습니다!",select_delete_file:"삭제할 파일을 선택하세요!",upload_desc_ncs:"마우스로 파일/메일을 끌어오세요.",
file_delete_fail_desc:"파일 삭제에 실패하였습니다.",shorcut_line:"라인 바로가기",translate_report_subject:"번역 결과 오번역에 대한 신고",
translate_report_body:"원문: 번역할 내용을 여기에 입력하세요. <br>번역문:",image_capture:"이미지편집",no_image:"등록된 이미지가 없어 메일 본문에 이미지를 삽입할 수 없습니다",
already_image_open:"이미 열려있는 이미지 편집창이 있습니다.",hide_write_header:"메일상단 접기",show_write_header:"메일상단 펼치기",
quick_attach:"빠른첨부",save_temp:"임시저장",do_save:"저장하기",saved_tome:"파일을 내게쓴메일함에 저장했습니다.",pause_uploader:"<span class='icon_pause'></span>일시중지",
restart_uploader:"다시시작",cancel_send_noti:'발송 대기 중 입니다.&nbsp;&nbsp;<a href="javascript:;" class="send_cancel _c1(mlCore|cancelReserveMailFromNoti|{messageID})">발송취소</a><a href="javascript:;" style="{showMailLink}" onclick="mrCore.readMailFromCancelNoti(\'{messageID}\')">메일보기</a>',
cancel_complete:"발송 취소 되었습니다.",open_attach:"파일첨부 열기",close_attach:"파일첨부 닫기",attach_not_saved:"임시저장시 대용량 파일과 약속잡기 설정은 저장되지 않습니다.\n메일을 임시저장하시겠습니까?",
open_attach_after_save:"임시저장 후에 첨부된 파일을 열어볼 수 있습니다. 임시저장하시겠습니까?",cannot_open_bigfile:"대용량파일은 쓰기 페이지에서 열어볼 수 없습니다.",
dblclick_to_open_attach:"파일명 더블 클릭시 파일열기",template_delete:"템플릿 삭제",template_bigfile_save:"템플릿 저장 시 대용량 파일은 저장되지 않습니다.\n템플릿을 저장하시겠습니까?",
template_security_reservation:"약속잡기, 보안등급, 발송예약을 설정한 메일은 템플릿으로 저장할 수 없습니다. \n설정 해제 후 저장해주세요.",template_security_reservation_naver:"약속잡기, 발송예약을 설정한 메일은 템플릿으로 저장할 수 없습니다. \n설정 해제 후 저장해주세요.",
template_exceed_20:"템플릿은 최대 20개까지 저장할 수 있습니다.",template_subject_duplicate:"기존 템플릿 제목과 동일하면 덮어쓰기 됩니다.",
template_no_content:"입력된 내용이 없어 템플릿으로 저장할 수 없습니다.\n내용 입력 후 저장해주세요.",template_delete_desc:"템플릿 메일은 삭제하면 복구할 수 없습니다.\n템플릿을 삭제하시겠습니까?",
template_no_subject:"템플릿 제목을 입력하세요.",join_web_message:"메시지",naumgothic:"나눔고딕",nanumcourier:"나눔명조",nanumsquare:"나눔스퀘어",
write_each:"개인별",eoo:""},o:{read_option:"읽기 설정",view_option:"보기 설정",write_option:"쓰기 설정",security_option:"보안접속 설정",
folder_option:"메일함 관리",smart_option:"스마트메일함 분류정보",cafe_option:"카페 설정",filter_option:"메일 자동 분류",filter_option_new:"메일 자동 분류",
sign_option:"서명 설정",signNW_option:"서명 설정",quickReply_option:"빠른 답장 설정",autoreply_option:"부재 중 설정",mobile_option:"새 메일 알림 설정",
remind_option:"리마인드 설정",setspam_option:"스팸 설정",rejectKeyword_option:"키워드 차단",receive_option:"수신허용/차단",
rejectAddress_option:"수신 차단/해제",externalMail_option:"외부 메일 가져오기",externalImap_option:"IMAP 메일 이전",externalUpload_option:"메일 업로드",
emlImport_option:"메일 업로드",idomain_option:"개인 도메인 메일 설정",pop3_option:"POP3/SMTP 설정",imap_option:"IMAP/SMTP 설정",
shortcut_option:"단축키",change_option:"설정변경",set_use:"사용 설정",set_unuse:"사용 안 함 설정",spam_folder_hide:"숨기기 설정",
spam_folder_show:"표시 설정",sign:"서명",set_sign:"서명 설정",nametag_sign:"네임택 서명",mail_nametag_sign:"메일네임택 서명",
add_sign:"서명추가",my_blog_sign:"내 블로그 서명",use_sign:"사용함",no_use_sign:"사용안함",my_sign:"내 서명",sign_desc:"내 서명은 최대 <em>3개</em>까지 만들 수 있습니다.",
works_sign_desc:"<strong>등록된 서명이 없습니다.</strong><p>'서명 만들기'를 눌러 서명을 등록해 주세요.</p>",use_sign_for_nwe:"새 메일 서명으로 사용",
use_sign_for_refw:"답장, 전달 서명으로 사용",sign_btn_area:"서명 수정/삭제/미리보기",blog_sign:"블로그 서명",set_sign_for_new:"새메일 서명 설정",
set_sign_for_refw:"답장, 전달 서명 설정",no_sign_name:"서명 이름을 입력해 주세요",no_sign_content:"서명 내용을 입력해 주세요",no_personal_sign:"직접 입력한 서명이 없습니다",
select_sign:"서명을 선택하여 주세요",delete_sign:"선택된 서명을 지우시겠습니까?",sign_size_limit:"서명 내용은 5,000bytes 이내로 입력해 주십시요.",
sign_count_limit_3:"서명은 최대 3개까지 만들 수 있습니다.\n\n다른 서명을 수정해서 사용해 주세요.",nametag_image:"네임택 이미지",use_nametag:"네임택 사용하기",
copy_nametag:"네임택이 복사되었습니다.\nCtrl + V 를 누르시면, 붙여넣으실 수 있습니다.",select_personacon:"사용하실 퍼스나콘을 선택하세요!",address:"메일주소",
domain:"도메인",block_addr_default_text:"예) id@domain.com",block_domain_default_text:"예) domain.com",already_exist_cafe_folder_name:"직접 추가한 메일함 중 같은 이름의 메일함이 존재합니다.\n\n기존 메일함의 이름을 바꾸어야 새로운 카페 메일함을 \n\n사용하실 수 있습니다.",
reject_list:"수신이 차단된 메일주소/도메인",type_reject_domain:"수신차단에 추가할 도메인을 입력해 주세요.",type_reject_address:"수신차단에 추가할 주소를 입력해 주세요.",
reject_count_limit:"수신차단에 추가할 수 없습니다.\n수신차단은 메일주소 및 도메인을 합하여 1000개까지 가능합니다.",reject_count_limit_confirm1:"수신차단 제한 개수 1000개를 초과하여 선택한 메일을\n수신차단 리스트에 추가하지 못하였습니다.\n수신차단 목록을 확인하시겠습니까?",
reject_count_limit_confirm2:"수신차단 제한 개수 1000개를 초과하여\n일부 메일을 수신차단 목록에 추가하지 못했습니다.\n수신차단 목록을 확인하시겠습니까?",
cannot_add_mine_to_reject:"본인의 메일 주소는 수신차단목록에 추가할 수 없습니다.",invalid_mail_domain_format:"<{Value}> 는 메일주소 또는 도메인 형식에 맞지 않습니다.",
invalid_domain_format:"<{DomainValue}> 는 도메인 형식에 맞지 않습니다.",select_delete_item:"삭제할 항목을 선택하세요!",delete_reject_all:"수신차단주소를 전체 삭제하시겠습니까?",
full_reject_list_delete_old_reject_address:"<em>수신거부메일 <span>1000</span>건이 모두 등록 되었습니다.</em> <br>환경설정&gt;수신거부에서 오래된 메일 주소를<br> 삭제해주세요.",
reject_my_addr:"본인 주소는 추가할 수 없으며 본인이 소속된 그룹메일 주소만 추가할 수 있습니다.",cannot_add_own_addr:"자신의 이메일 주소는 추가할 수 없습니다.",
new_mailbox_name_limit:"(20자까지 입력 가능)",mobile_number:"휴대폰 번호",delete_mobile_auth:"휴대폰 인증을 삭제하시겠습니까?",
register_cellphone_for_sms:"휴대폰 정보를 등록하셔야 문자\n알람을 받을 수 있습니다.",deleted_auth:"삭제되었습니다.",idomain_mail:"개인 도메인 메일",
invalid_idomain_mail_format:"메일주소는 영문자, 숫자,-,_,.(마침표)\n만 사용가능합니다.",invalid_idomain_domain_format:"도메인명은 영문자, 숫자,-,.(마침표)\n만 사용가능합니다.",
invalid_idomain_mail_length:"메일주소는 최소 2자 ~ 최대 20자까지 입력할 수 있습니다.",invalid_idomain_domain_length:"도메인명은 최소 2자 ~ 최대 63자까지 입력할 수 있습니다.",
cannot_use_forbidden_idomain_name:"naver, hangame, nhn이 포함된 도메인 명을 사용할 수 없습니다.",mail_address_length_limit_256:"메일주소는 최대 256자까지 입력할수 있습니다.",
type_correct_domain_format:"도메인 형태는 example.com 과 같은 형태로 입력해주세요.",nonexitst_domain:"존재하지 않는 도메인입니다.\n도메인 등록 후 다시 설정해 주세요.",
cancel_idomain:"취소 시 등록 및 확인된 모든 내용이 초기화됩니다.\n등록을 취소하고 처음 단계로 이동하시겠습니까?",close_idomain:"해제하면 개인 도메인 메일함을 내 메일함으로 이동하며,\n개인 도메인 메일주소로 수신 및 발신이 제한됩니다.",
refer_default_mail_to_write:"기본 메일은 메일 쓰기 시 기본으로 선택되는 메일 주소입니다.",idomain_set_stage:"의 도메인 확인 및 설정 단계입니다.",
identify_idomain_own:"도메인 보유 여부를 확인하기 위해 아래 안내에 따라 설정해 주세요.",registered_cname:"등록할 CNAME",indecated_domain_by_cname:"CNAME이 가리킬 도메인",
using_idomain:"개인 도메인 메일을 사용하고 있습니다.",not_using_idomain:"개인 도메인 메일의 사용이 중단되었습니다.",my_option_info:"내 설정 정보",
view_related_help:"관련 도움말 보기",error_on_idomain:"의 도메인 설정에 오류가 있습니다.",confirm_valid_mxrecord:"도메인 관리 업체에 MX레코드 설정 값이 올바르게 등록되었는지 확인해 주세요.",
confirm_valid_cname:"도메인 관리 업체에 CNAME 설정 값이 올바르게 등록되었는지 확인해 주세요.",mxrecord:"MX 레코드",my_setted_cname:"회원님의 CNAME 설정값",
wanting_id:"원하는 아이디",having_domain:"보유하신 도메인",use_bill_folder:"청구서 사용",type_receive_address:"수신허용에 추가할 주소를 입력해 주세요.",
receive_count_limit:"수신허용에 추가할 수 없습니다.\n수신허용은 메일주소 및 도메인을 합하여 {MaxReceiveCount}개까지 가능합니다.",already_exist_content:"동일한 내용이 이미 존재합니다. 다시 확인해 주세요.",
registered_spam_keyword:"등록된 스팸 키워드",type_spam_keyworkd:"스팸 키워드를 입력해 주세요.",reject_spam_count:"스팸 키워드를 추가할 수 없습니다.\n스팸 키워드는 {MaxSpamCount}개까지 가능합니다.",
agree_information_offer:"고객정보 제공에 동의하셔야 합니다.",auto_reply_size_limit_4000:"답장내용은 4000 bytes 이내로 입력해 주십시요.\n\n현재크기는 {BodyLength} bytes 입니다.",
already_exist_fromname:"입력하신 이름이 이미 보내는 이름 목록에 있습니다.\n다른 이름을 입력해 주세요.",type_fromname:"이름을 입력하세요.",delete_name:"이름 삭제",
absence_interval_limit_3:"부재 중 설정은 최대 3년간 가능합니다.",invalid_absence_interval:"부재 중이 끝나는 날이 시작날보다 작습니다.",
no_filter_cond:"저장할 필터조건이 없습니다.",no_filter_refer_add_filter:"아직까지 지정된 분류가 없습니다.<br>'분류추가'버튼을 눌러서 추가하실 수 있습니다.",
delete_filter:"정말 삭제하시겠습니까?",over_limit_add_filter:"이미 {CurrentCount}개의 분류항목이 등록되어 {RestCount}개의 항목만 추가 가능합니다. 추가할 항목을 다시 선택해 주세요.",
find_filter_count:"<em>{Count}</em>개의 항목이 검색되었습니다",refer_find_option:"분류 항목을 검색하거나 조건별로 선택해서 볼 수 있습니다.",
filter_included_addres:"이미 등록된 주소입니다.",filter_to_address:"받는사람 주소",filter_from_address:"보낸사람 주소",filter_cc_address:"참조 주소",
filter_to_cc_address:"받는사람 또는 참조 주소",filter_remove:"제거",filter_addr_10_limit:"메일 주소는 10개까지 입력할 수 있습니다",
filter_or_desc:"또는",filter_dimmed_desc:"같은 기준 리스트에 메일 주소를 2개 이상 등록하여\n기존 메일 적용이 비활성화 되었습니다.",filter_addr_no_address:"메일 주소를 입력해 주세요.",
filter_addr_header_edit:"분류 수정",filter_addr_header_add:"분류 추가",filter_addr_or_domain:"메일주소 또는 도메인",one_select_filter_list:"1개의 분류 목록을 선택해 주세요.",
already_located_on_top:"이미 목록 맨 위에서 제공되고 있습니다.",already_located_on_bottom:"이미 목록 맨 아래에서 제공되고 있습니다.",
apply_rule_exist_mail:"기존 메일도 변경된 분류 기준을 적용할까요?",input_forward_email_addr:"'입력한 메일 주소로 전달'을 선택하고\n메일 주소를 입력하지 않았습니다.\n입력 후 저장 버튼을 다시 눌러 주세요.",
restrict_forwarding:"메일을 전달할 주소는 하나만 입력할 수 있습니다.",input_new_folername:"'새 메일함에 저장'을 선택하고\n메일함 이름을 입력하지 않았습니다.\n입력 후 저장 버튼을 다시 눌러 주세요.",
input_filter_semiconlon:"세미콜론(;)은 입력할 수 없습니다.",input_filter_condition:"설정한 조건이 없습니다.\n분류 기준과 처리 방법을 선택하시고 저장 버튼을 눌러 주세요.",
input_filter_step1_cond:"분류 기준을 선택하지 않았습니다.\n‘1단계 분류 기준’을 선택해 주세요.",input_filter_step2_cond:"처리 방법을 선택하지 않았습니다.\n‘2단계 처리 방법’을 선택해 주세요.",
input_filter_address_validation:"메일주소를 다시 확인해 주십시오.",msg_filter_search:"분류기준 및 처리방법을 검색해보세요.",select_a_rule:"분류 기준 개별 선택",
apply_org_mail_desc:"<em>* 내가 쓴 메일에 대한 답장</em>을 선택한 경우는 <strong>기존 메일에 설정한 분류기준을 적용할 수 없습니다.</strong>",
read_all:"모두 읽음 표시",read_all_folder:"{FolderName} 의 안 읽은 메일이 모두 읽음으로 표시됩니다.\n\n모두 읽음으로 표시하시겠습니까?",recovered_folder_fast:"빠른 메일함 복구를 하였습니다.",
total_folder_count:"총메일함 수",view_whole_mail:"전체메일 보기",view_unread_mail:"안읽은 메일만 보기",view_attach_mail:"첨부메일만 보기",
view_remind_mail:"리마인드메일만 보기",view_important_mail:"중요메일만 보기",view_tome_mail:"내가 받는사람인 메일만 보기",using_imap:" 님은 현재 IMAP/SMTP를 사용하고 있습니다.",
not_using_imap:" 님은 현재 IMAP/SMTP를 사용하고 있지 않습니다.",if_using_imap:"<br>아래에서 설정을 변경하시면 IMAP/SMTP를 사용하실 수 있습니다.",
not_using_imap_ncs:" 님은 현재 IMAP/SMTP를 사용하고 있지 않습니다.",using_pop3:" 님은 현재 POP3/SMTP를 사용하고 있습니다.",not_using_pop3:" 님은 현재 POP3/SMTP를 사용하지 않습니다.",
if_using_pop3:"<br>POP3/SMTP를 사용하려면 [POP3/SMTP 사용]을 [사용함]으로 설정하세요.",copy_address:"주소가 복사되었습니다.\nCtrl + V 를 누르시면, 붙여넣으실 수 있습니다.",
set_leave_original_mail:"'원본 저장' 방식을 설정해 주세요.",externalMail_count_limit_10:"최대 10 개까지만 등록할 수 있습니다.",
quick_tab:"빠른 선택",direct_tab:"직접 입력",leave_original:"원본 남기기 : ",apply_auto_filter:"자동 분류 설정 적용 : ",apply_spam_setting:"스팸 설정 적용 : ",
retrieve_contacts:"주소록 가져오기 : ",auto_retrieve_mail:"외부 메일 자동으로 가져오기 : ",confirm_detail_setting:"※ 등록 후 외부 메일 목록에서 상세설정된 내용을 반드시 확인해 주세요.",
yes:"예",no:"아니오",type_pop3_server:"POP서버를 입력해 주세요.",type_server_address:"서버주소를 입력하세요",type_id:"아이디를 넣어주세요.",
type_password:"비밀번호를 넣어주세요.",receive_mail_after_date:"이전에 설정한 시간 이후 수신한 메일만 받음",type_mail_addrees_instead_id:"아이디 대신 메일주소를 입력해 주세요.",
invalid_id_retry:"아이디(메일주소)가 잘못 입력되었습니다. 다시 확인 후 정확하게 입력해 주세요.",cannot_add_own_lw_email:"현재 이용 중인 LINE WORKS 계정은 등록할 수 없습니다.\n입력한 계정을 확인해주세요.",
id_length_limit_100:"입력할 수 있는 아이디 길이를 초과하였습니다.(100자 이내)",agree_account_information_offer:"외부 메일의 계정정보 이용에 동의해주십시오.",
cannot_use_pop3_service:"외부메일(POP3)을 지원하지 않는 서비스입니다. 해당 메일 서비스에서 확인해 주세요.",invalid_address_refer_valid_address:"잘못된 주소입니다. 올바른 주소 : ",
invalid_mail_address:"올바른 E-mail 주소가 아닙니다.",saved_setting:"설정이 저장되었습니다.",input_only_id:"아이디만 입력해 주세요.",
use_only_paid_member:"위 메일은 유료 회원인 경우만 메일을 가져올 수 있습니다.",use_only_setted_pop3:"해당 계정에서 POP사용 설정을 한 경우만 메일을 가져올 수 있습니다.",
example_pop3:"예) pop.naver.com",select_confirm_wanted_pop3:"* 확인을 원하는 외부메일의 POP 주소를 선택합니다.",cannot_register_mail_account:"현재 이용중이신 네이버 계정은 등록이 불가능합니다. 등록하신 계정을 다시 확인해주세요.",
terminated_service:"서비스 종료",unavailable_servie:"서비스 불가",again_register:'<p>계정 전환을 한 경우 "삭제" 후 전환된 계정으로 재등록 해주세요.</p>',
cannot_my_account:"<p>본인의 네이버 메일 계정은 외부메일로 가져올 수 없습니다.</p>",input_mail_addr:"메일 주소를 넣어주세요.",completed_registration:"외부 메일 등록이 완료되었습니다.",
agreement_required_alert:"개인정보 제공에 동의하기 전,\n만 14세 미만의 어린이는 보호자 동의절차가 필요합니다.\n휴대폰 인증 또는 i-PIN 인증을 통해\n보호자 동의받기를 먼저 진행해주세요.",
agreement_require_user_guide:"14세 미만 사용자는 환경설정에서 보호자 동의 후,\n외부 메일 가져오기 설정이 가능합니다.",samsung_card:"삼성카드",
lg_card:"LG카드",shinhan_card:"신한카드",hyundai_card:"현대카드",yes_card:"Yes카드",bc_card:"비씨카드",kb_card:"KB카드",
galleria_card:"갤러리아카드",olleh:"olleh",lg_u_plus:"LG U<sup>+</sup>",lg_powercom:"(LG파워콤)",lg_dacom:"(구.LG데이콤)",
sky_life:"SkyLife",tu_media:"TUMedia",onse_telecom:"세종텔레콤",sk_broadband:"SK브로드밴드",receive_bill:"청구서 수신",
until_withdraw_member_end_service:"회원 탈퇴 및 서비스 종료 시까지",save_edited_option:"환경설정이 수정되었습니다.",only_use_IE:"죄송합니다. Internet Explorer 에서만 이용하실 수 있습니다.",
already_used_shortcut:"입력하신 단축키는 이미 다른 단축키로 사용되고 있습니다.",must_include_functionkey:"해당 단축키는 <CTRL>, <ALT> 중 하나를 반드시 포함해야 합니다.",
cannot_use_in_ie6:"Internet Explorer 6, 7 버전의 경우, \n네이버 메일을 사용할 수 없습니다.",update_for_using:"사용을 원하시면, 브라우저 버전을 업데이트해주세요.",
reject_by_admin:"<br>본 기능은 관리자에 의해서 비활성화 될 수 있습니다.",agree_parent_offer_desc:"개인정보 제공에 동의하기 전,\n만 14세 미만의 어린이는 보호자 동의절차가 필요합니다.\n휴대폰 인증 또는 i-PIN 인증을 통해\n보호자 동의받기를 먼저 진행해주세요.",
input_connection_port_desc:"연결포트를 입력해 주세요",add_1gb_event_desc:"외부메일 등록이 완료되어\n1GB 추가 이벤트에 참가되었습니다",emphasis_color_desc:"강조색상을 선택해 주세요",
external_select:"선택하세요",external_lineworks:"LINE WORKS",external_naver:"네이버",external_nate:"네이트",external_shinbiro:"신비로",
external_yahoo:"야후(com)",external_gmail:"구글(지메일&G Suite)",external_daum:"다음(한메일)",external_hotmail:"핫메일(아웃룩메일)",
external_kebi:"깨비메일(유료)",external_unitel:"유니텔(유료)",external_chol:"천리안(유료)",external_korea:"Korea.com(유료)",
external_direct:"직접입력",select_move_mail_desc:"이동할 메일함을 선택해 주세요.",request:"신청하기",no_assigned_vip:"VIP로 지정된 주소가 없어 설정을 할 수 없습니다.\n주소록에서 VIP(중요 연락처)를 지정하시겠습니까?",
select_mailbox:"메일함이 선택되지 않았습니다.\n메일함을 선택해주세요.",auth_success:"전달 받을 메일 주소가 인증 되었습니다.",no_auth_mail_input:"전달 받을 메일 주소를 입력하지 않았습니다.",
not_certify_number:"인증번호가 잘못되었습니다.",send_auth_mail:"전달 받을 메일 주소로 인증 번호가 포함된 메일을 발송하였습니다.",auth_fail:"'입력한 메일 주소로 전달' 선택 후 메일 인증이 되지 않았습니다.\n전달 받을 주소로 발송된 인증 번호로 메일 인증 후 저장 버튼을 다시 눌러 주세요.",
only_ncs:"NCS 사내 메일 주소로만 전달이 가능합니다. ",only_nwe:"도메인 내 주소로만 전달이 가능합니다.",input_auth:"인증번호 입력",invalid_mail_format:"메일 형식이 잘못되었습니다.",
invalid_imap_host:"IMAP 서버 주소가 잘못되었습니다. 다시 입력해주세요.",invalid_imap_port:"연결 포트가 잘못 입력되었습니다. 다시 입력해주세요.",
invalid_imap_port_format:"포트 번호는 숫자만 입력할 수 있습니다.",invalid_imap_user:"IMAP 메일주소나 비밀번호가 잘못되었습니다. 다시 입력해주세요.",
upload_eml_only:"확장자가 EML인 파일만 업로드 할 수 있습니다.",imap_fail1:"IMAP 서버로 연결이 되지 않습니다. 입력된 정보를 다시 확인해주세요",confirm_cancel_imap:"메일 이전을 중단하겠습니까?",
alert_leaving_upload:"이 페이지를 벗어나면 업로드가 중단됩니다.",imap_fail:"메일 이전 실패",imap_complete:"{EndTime} 완료",cannot_upload_ndrive:"드라이브 파일은 추가할 수 없습니다.",
file_not_selected:"파일을 선택해주세요.",sign_addr_count_limit:"회사 주소는 최대 10개까지 등록할 수 있습니다.",sign_invalid_sign_name:"서명 이름을 입력하세요.",
sign_invalid_name:"이름을 입력하세요.",sign_invalid_addr:"회사 주소를 입력하세요.",sign_invalid_content:"내용을 입력하세요.",sign_invalid_image:"사용할 이미지를 선택해주세요.",
sign_invalid_phone:"전화번호에는 1자 이상의 숫자와 -,*,#,+,P,T,(,)만 입력할 수 있습니다.",sign_confirm_delete_addr:"주소를 삭제하시겠습니까?",
sign_image_size_limit:"로고 이미지는 300KB 이하의 파일만 등록하실 수 있습니다.",sign_image_size_limit2:"가로/세로 195px 이하인 이미지만 등록 가능합니다.",
sign_image_type_limit:"이미지 파일(bmp,jpg,jpeg,png,gif)만 등록할 수 있습니다.",sign_image_count_limit:"로고 이미지는 5개까지 등록할 수 있습니다.",
sign_no_auth:"권한이 없습니다.",sign_template_count_limit:"공통 서명은 최대 3개까지 만들 수 있습니다.",sign_direct_input:"직접 입력",
sign_invalid_url:"이미지 URL을 입력해주세요.",sign_btn_addr_layer:"'추가' 버튼을 눌러 회사 주소를 입력하세요.",sign_name_desc:"서명 이름은 최대 10자까지 입력 가능",
sign_name_desc2:"서명 이름은 최대 10자까지 입력 가능합니다.",sign_additional_info_desc:"추가문구를 입력해주세요",sign_del_image_desc:"이미 서명에 사용되고 있는 이미지를 삭제하는 경우, 기존 발송된 메일에서 해당 이미지가 엑박으로 나타날 수 있습니다. 이미지를 삭제하시겠습니까?",
sign_not_found:"서명이 삭제되어 수정할 수 없습니다.",sign_reset_desc:"기존 편집내용은 유지 되지않습니다. 새로운 작업을 하시겠습니까?",sign_copy_clipboard:"클립보드에 복사되었습니다.",
sign_check_addr:"주소 선택",sign_edit_addr:"주소 수정",sign_img_desc:"<span class='ico_dot' ></span>도메인 당 공통 이미지는 10개까지 등록하여 사용하실 수 있으며, 이 서명에서 5개까지 삽입 가능합니다.",
sign_img_desc_free:"<span class='ico_dot' ></span>도메인 당 공통 이미지는 10개까지 등록하여 사용하실 수 있습니다.",sign_img_add:"이미지 등록하기",
sign_length_limit:"{Item}에 텍스트는 {MaxLength}자까지 입력가능합니다.(현재{CurrentLength}자)",sign_name:"이름",sign_department:"부서",
sign_position:"호칭",sign_address:"회사주소",sign_additional_info:"추가문구",font_size_verylarge:"아주 크게",font_size_large:"크게",
font_size_normal:"보통",font_size_small:"작게",font_size_verysmall:"아주 작게",editor_mode_1_h:"에디터(이전)",editor_mode_1_t:"텍스트(이전)",
editor_mode_2_h:"에디터",editor_mode_2_t:"텍스트",unuse_smart_title:"{FolderName} 사용 안 함",unuse_smart_message:"{FolderName} 사용을 중지하시겠습니까?<br><br>{FolderName} 메일함이 비활성화되며,<br>메일함에 있던 메일은 받은메일함으로 이동됩니다.",
eoo:""},c:{mail:"메일",ncs_mail:"메일",naver_mail:"네이버 메일",nwe_mail:"메일",ad:"광고",set:"설정하기",select:"선택하기",
selected:"선택됨",complete:"완료",pause:"중지",fail:"실패",processing:"진행중",use:"사용하기",edit:"수정",edit_2:"수정",
cancel:"취소",save:"저장",del:"삭제",del_2:"삭제",backup:"백업",reset:"리셋",send:"보내기",empty:"비우기",unfold:"펼치기",
fold:"접기",open:"열기",close:"닫기",first:"처음",end:"끝",prev:"이전",next:"다음",reserve:"예약",wait:"대기",sending:"발송",
reservewait:"예약/대기",name:"이름",address:"주소",email:"이메일",noname:"이름없음",phone_number:"전화번호",sender_simple_search:"보낸사람",
receiver_simple_serach:"받는사람",content_simple_search:"내용",re_sender_simple_search:/^보낸사람:/,re_receiver_simple_serach:/^받는사람:/,
re_content_simple_search:/^내용:/,sender:"보낸사람",receiver:"받는사람",sender_receiver:"보낸/받는사람",sender_2:"보낸 이",
receiver_2:"받는 이",sender_3:"보내는사람",cc:"참조",bcc:"숨은참조",id:"아이디",pass:"비밀번호",save_id:"아이디저장",login:"로그인",
content:"내용",case_num:"건",unit:"개",unit2:"개",size:"용량",size_2:"메일크기:",list:"목록",example:"예",empty_frame:"빈프레임",
search_keyword:"검색어",help_topic:"도움말",divide_arrow:"구분 화살표",directly_type:"직접입력",detail_view:"자세히보기",
not_see_7_days:"7일간 보지 않음",not_see_again:"다시 보지 않음",mail_read:"메일 읽기",mail_write:"메일 쓰기",mark_mail:"중요메일",
normal_mail:"일반메일",mark_inportant_mail:"중요메일로 표시하기",unmark_inportant_mail:"중요메일로 표시됨, 중요메일 해제하기",select_all:"전체선택",
unselect_all:"전체해제",cancel_select:"선택해제",caution:"주의",search_employee:"사원검색",download:"다운로드",prev_mail:"이전 메일",
prev_mail2:"이전 메일",hide:"숨기기",reply:"답장",reply_all:"전체답장",forward:"전달",add_func:"추가기능",open_layer:"레이어 열림",
more:"더보기",more_by_sender_view:"더보기",all_by_sender_view:"전체보기",descend_sort:"내림차순으로 정렬",ascend_sort:"오름차순으로 정렬",
get_external_mail:"외부메일 가져오기 진행중..",no_external_mail:"가져 온 외부메일이 없습니다.",process_status:"진행상태",last_access_time:"마지막 접속시간",
terminate_service:"서비스 종료",deny_service:"본인 메일 계정 서비스 불가",fail_over_size:"<strong class='fail'>실패</strong>(40MB 초과 메일 {overSizeCount}개)",
search_result:"검색결과",search_mail:"메일검색",reSearch_count_limit:"결과 내 재검색은 최대 5회까지 가능합니다.",search_length_limit_120:"한글 기준으로 최대 120자까지 검색할 수 있습니다.",
search_result_title:"메일 검색 결과",type_search_keyword:"검색어를 입력하세요",type_search_keyword_length_2:"검색어를 두글자 이상 입력하셔야 검색결과를 확인하실 수 있습니다.",
type_the_subject:"제목을 입력해 주세요",date_length_8:"날짜는 8자리의 숫자로 입력하셔야 합니다.",input_start_date_format:"시작일을 YYYYMMDD 형식으로 입력해주세요.",
invalid_start_date_format:"시작일이 올바르지 않습니다. YYYYMMDD형식으로 기입해주세요.",invalid_end_date_format:"종료일이 올바르지 않습니다. YYYYMMDD형식으로 기입해주세요.",
input_limit_100:"검색어는 100자까지 입력할 수 있습니다.",btn_refresh:"새로고침",btn_list_refresh:"메일목록 새로고침",simple_search_filter:/^보낸사람:|^받는사람:|^내용:|^"|&|\||!/,
delete_all:"전체삭제",search_keyword_save_off:"검색어저장 끄기",search_keyword_save_on:"검색어저장 켜기",recent_empty_search_keyword:"최근 검색어가 없습니다.",
keyword_save_function_off:"검색어 저장 기능이 꺼져있습니다.",search_from:"보낸사람",search_tocc:"받는사람+참조",search_to:"받는사람",
search_subject_body:"제목+본문",search_subject:"제목",search_body:"본문",search_content:"내용",search_attach:"첨부파일",
search_all:"전체",search_exact:"정확히 일치하는 내용",search_to_term:"받는사람",search_from_term:"보낸사람",search_content_term:"내용",
date_line_west:"(날짜 변경선 서쪽)",midway_islands_samoa:"(미드웨이 아일랜드, 사모아)",hawai:"(하와이)",marquesas:"(마퀘사스)",
alaska:"(알래스카)",pecan:"(피칸)",pacific_time:"(태평양 표준시)",mountain_time:"(산지 표준시_미국/캐나다)",central_time:"(중부 표준시_미국/캐나다)",
east_time:"(동부 표준시_미국/캐나다)",caracas:"(카라카스)",atlantic_time:"(대서양 표준시)",newfoundland:"(뉴펀들랜드)",buenos_aires:"(부에노스아이레스)",
central_atlantic:"(중앙 대서양)",azores:"(아조레스)",greenwich_mean_time:"(그리니치 표준시_런던)",amsterdam:"(암스테르담, 베를린, 빈)",
athens:"(아테네, 카이로)",moscow:"(모스크바, 바그다드)",teheran:"(테헤란)",baku:"(바쿠, 무스카트)",kabul:"(카불)",karachi:"(카라치)",
new_delhi:"(뉴델리, 뭄바이, 콜롬보)",kathmandu:"(카트만두)",astana:"(아스타나, 다카)",yangon:"(양곤)",bangkok:"(방콕, 하노이, 자카르타)",
beijing:"(베이징, 싱가폴, 타이베이)",seoul:"(서울, 도쿄)",darwin:"(다윈, 아델라이드)",guam:"(괌, 캔버라, 시드니)",rhode_island:"(로드 호우 아일랜드)",
new_caledonia:"(뉴 칼레도니아)",norfolk_island:"(노포크 아일랜드)",auckland:"(오클랜드,피지)",select_mail:"메일을 선택해 주세요!",
select_only_one:"1개의 메일을 선택해 주세요.",select_mail_num:"{sStatus}개의 메일을 선택했습니다.",select_mail_num_conversation:"{conversationCount}개의 대화 메일, {normalCount}개의 메일을 선택했습니다.",
templory_error:"일시적인 오류입니다. 잠시 후 다시 시도해 주세요.",select_marked_mail:"중요 메일을 선택해 주세요.",getting_thread_list:"주고 받은 메일 리스트를 가져오는 중...",
getting_list_from_folder:"{Name}의 리스트를 가져오는 중...",got_newmail:"새 메일이 도착하였습니다.",nomail_to_move:"이동할 메일이 없습니다.",
reject_selected_mail_address:"선택한 메일주소 수신 차단하기",show_help_page:"도움말 보기",finish_list_loading:"메일 리스트 그리기 완료!!",
elapsed_time:"경과시간",sunday:"일",monday:"월",tuesday:"화",wednesday:"수",thursday:"목",friday:"금",saturday:"토",
year:"년",month:"월",day:"일",hour:"시",hour2:"시간",hour3:"시",minute:"분",minute2:"분",second:"초",line_service_link:"라인 페이지 바로가기",
invalid_date:"날짜 범위를 벗어났습니다. 다시 입력해 주세요.",input_past_date:"오늘 이후의 날짜는 선택하실 수 없습니다.",invalid_start_date:"시작 날짜를 끝 날짜보다 빠르게 입력해 주세요.",
arranging_old_mail:"오래된 메일을 정리 중입니다.",arrange_select_before_date:"날짜선택",unread_mail_desc:"최근 안읽은 메일 <em>{allNum}</em>통 중 현재 <strong>{selectedNum}</strong>통 선택 ({percent}%)",
recently_received_mail_title:"최근 수신된 메일 제목",system_define:"시스템차단",system_move:"스팸자동이동",user_define:"사용자설정",
user_report:"스팸신고",user_move:"직접이동",tooltip_system:"스팸 필터로 자동 차단된 메일",tooltip_user:"환경설정 내 '스팸 설정' 으로 차단된 메일",
tooltip_report:"'스팸신고'를 통해 내가 직접 이동시킨 메일",tooltip_move:"'이동'을 통해 내가 직접 이동시킨 메일",reason_spam_folder:"이 메일이 스팸메일함에 있는 이유",
auto_naver_spam_filter:"스팸 필터로 자동 차단된 메일",spam_auto_move:"스팸 자동이동 사용",fault_report_spam:"실수로 스팸신고한 메일일 경우 ",
hear:"여기",please_click:"를 클릭해 주세요. ",clean_spam:"스팸 해제",user_direct_move:"직접 이동",fault_move_spam:"실수로 이동시킨 메일일 경우 ",
spam_setting:"스팸 설정",sender_address:"보낸 사람의 주소가 주소록에 없으면 스팸으로 자동 분류",above_spam:"위 스팸 설정을 해제하려면 ",shortcut_spam_setting:"스팸 설정 바로가기",
not_include:"받는사람, 참조(숨은참조)에 내 메일 주소가 없으면 스팸으로 자동 분류",my_naver_mail:"내 네이버 메일 주소를 사칭한 메일이 있으면 스팸으로 자동 분류",
language_chinese:"언어별 스팸 분류 설정 사용(중국어)",language_english:"언어별 스팸 분류 설정 사용(영어)",language_japanese:"언어별 스팸 분류 설정 사용(일본어)",
language_russian:"언어별 스팸 분류 설정 사용(러시아어)",language_all:"언어별 스팸 분류 설정 사용(모든 외국어)",shortcut_spam_keyword:"스팸 키워드 설정 바로가기",
block_spam_ad:"스팸 키워드 차단 (광고)",block_spam_adult:"스팸 키워드 차단 (성인)",block_spam_promotion:"스팸 키워드 차단 (홍보)",
block_spam_agreement:"스팸 키워드 차단 (동의)",block_spam_shopping:"스팸 키워드 차단 (쇼핑)",block_spam_loan:"스팸 키워드 차단 (대출)",
block_spam_user:"스팸 키워드 차단 (사용자 직접 입력 키워드)",auto_sort_rule:"메일 자동 분류 규칙",auto_sort_move:"에 의한 스팸메일함 이동",
change_regulation_rule:"분류 규칙을 변경하려면 ",external_rule:"외부메일 불러오기 설정",external_move:"에 의한 스팸메일함 이동",change_export_rule:"불러오기 설정을 변경하려면 ",
alert_cancel_spam_setting:"스팸 설정을 해제하고 해당 메일을 받은메일함으로 이동하시겠습니까?",alert_cancel_spam_keyword:"스팸 키워드를 해제하고 해당 메일을 받은메일함으로 이동하시겠습니까?",
display_doubt_spam:"이 메일은 스팸으로 의심되는 메일입니다. ",hide_doubt_spam:"이 메일은 스팸으로 의심되어 내용을 표시하지 않았습니다. ",display_spam_body:"메일 표시하기",
hide_spam_body:"메일 숨기기",set_spam_auto_move:"스팸 자동 이동 설정하기",set_spam_auto_move_report:"스팸 자동 이동이 설정되고 해당 메일을 스팸 신고 하였습니다.",
alert_not_select_mail:"정리할 메일이 선택되지 않았습니다.",alert_delete_mail_permanently:"선택한 메일주소로부터 온 메일들이 영구삭제 됩니다.",
msg_move_trash_mail:"삭제된 메일은 휴지통으로 이동됩니다.",msg_deleted_mail_permanently:"삭제된 메일은 영구삭제되며, 복구가 불가능합니다.",
msg_clean_request_complete:"요청이 완료되었습니다.\n정리할 메일의 개수에 따라 처리시간이 길어질 수 있습니다.",arrange_no_list:"정리할 메일이 없습니다.",
promotion_banner:"프로모션 배너",promotion_banner_close:"프로모션 영역 닫기",open_new_window:"새 창으로 열기",login_slogan_desc1:"네이버에 로그인할 땐 주소창에 https 확인!",
login_slogan_desc3:"이번 달 카드 명세서가 궁금하다면?",login_slogan_desc4:"흩어져 있던 나의 메일을 한 곳에서 모아보기",login_slogan_desc5:"쇼핑/뉴스/자동 청구서 메일을 쏙쏙 자동 분류하기",
login_slogan_desc6:"네이버 메일 사용자라면 보안 걱정은 No!",login_slogan_desc7:"많은 양의 오래된 메일 한 번에 싹 ~ 정리하기",login_slogan_desc8:"위젯으로 편리하게! 스킨으로 특별하게!",
login_slogan_desc9:"중요 메일은 색상으로 강조하기!",control_load_fail_desc:"컨트롤 로드 실패",already_installed_desc:"이미 설치되어 있음",
not_installed_desc:"설치되어 있지 않음",install_ocx_desc:"ocx를 설치하셔야 합니다.",more_numbers_exit:"외  {Number} 개",
sleep:"(휴면)",del_3:"지우기",change_sign_desc:"서명을 변경하시면 기존 서명 영역 내의 수정한 내용도 모두 삭제됩니다.\n서명을 변경하시겠습니까?",unblock_popup_desc:"팝업차단을 해제해주세요",
works_contacts:"LINE WORKS 연락처",mailing_group:"메일링그룹",blog_sign2:"블로그서명",mail_nametag:"메일 네임택",type_message_desc:"메시지를 입력해 주세요.",
bigfile_uploader_install:"대용량 업로더 <span style='color:#00Bf48; text-decoration:underline;'>설치</span>하기",
go_to_promotion_page:"프로모션 페이지로 이동하기",works_archive:"[보관]",works_import_desc:"기존 Works 메일 가져오기 설정이 저장되었습니다. 주기적으로 메일을 순차적으로 가져옵니다.",
works_import_complete_mailbox:"<strong>{folderName}</strong> 메일함으로 <strong>{mailCount}</strong>개 메일 가져오기 완료",
works_import_complete_time:"마지막 가져오기 시도 시간",works_authentication_fail:"인증실패",works_now_importing:"기존 Works 메일 가져오기 진행중입니다.",
works_input_pass_desc:"연동된 네이버 비밀번호를 입력해 주세요.",works_input_pass_modify_desc:"수정이 필요한 경우만 입력해주세요.",address_layer_import_checked:"자주사용하는 주소 체크됨",
address_layer_import_nochecked:"자주사용하는 주소 체크안됨",address_layer_groupselect_open:"그룹 선택 레이어 열기",address_layer_name:"추가할 이름",
address_layer_default:"전체연락처",namelessness:"이름없음",eoo:""},e:{examination_error:"보다 안정적인 서비스 환경을 만들기 위해 현재 메일 서비스를 점검 중입니다.\n이용에 불편을 드린 점 진심으로 사과 드리며, \n예정된 시간 안에 점검을 마칠 수 있도록 최선을 다하겠습니다.",
api_response_error:"API응답 오류",temporary_error:"일시적인 오류가 발생하였습니다. 잠시 후 다시 시도해 주세요.",fail_to_send:"일시적인 오류로 메일을 정상 발송할 수 없습니다.",
invalid_referer_error:"보안 정책에 따라 기능이 제한됩니다.",fail_to_save:"임시보관함에 저장 실패.",last_save_time:"최종 저장시간",login_info_changed:"로그인 정보가 변경되었습니다.\n확인을 누르시면 페이지가 새로 고침되어 변경된 정보를 확인하실 수 있습니다.",
temporary_system_error:"일시적인 시스템 오류가 발생하였습니다.\n서비스 이용에 불편을 드려 대단히 죄송합니다.\n잠시 후 다시 시도해 주십시오.",acp_time_out:"서버와의 통신이 제한 시간을 초과하였습니다.",
sso_no_empmail:"아파치 header에 EMPMAIL 항목이 존재하지 않습니다.",reserved_foldername:"시스템에서 사용하는 메일함입니다. 다른 이름으로 입력해 주세요.",
common_parameter_error:"잘못된 사용자 파라미터 요청입니다.",common_external_http_error:"HTTP 외부 연동 응답 오류입니다.",common_not_supported_method:"지원되지 않는 메소드 호출입니다.",
common_empty_string:"특별한 메세지가 없습니다.",mail_not_exist:"메일이 존재하지 않습니다. 해당 메일은 삭제 되었거나 \n보낸사람이 발송 취소 하였습니다.",
mail_not_exist_readreceipt:"선택하신 메일은 삭제되거나 보낸메일함에 저장하지 않은 메일입니다.",mail_not_included_folder:"메일함 정보가 없어 메일을 열 수 없습니다.\n메일을 원하시는 메일함에 이동 후 메일을 다시 확인해주세요.",
read_mail_fail:"존재하지 않는 메일입니다.",write_timeout:"쓰기 로딩 시간이 초과되었습니다. 잠시 후 다시 시도해주세요.",send_no_attachid:"첨부파일 정보가 없습니다.",
send_referrer_error:"비정상적인 메일 발송입니다.",send_no_recipient:"수신자가 없습니다.",send_exceed_max_recipient:"최대 수신인 제한수를 초과하였습니다.",
send_wrong_email_format:"수신자의 주소형식이 잘못되었습니다.",send_wrong_mailsn:"원본메일 정보가 존재하지 않습니다.",send_check_amount_error:"발송 제한을 초과하였습니다.",
send_bigfile_error:"대용량 파일 서버의 일시적인 장애로 메일을 보내지 못했습니다.\n대용량 파일을 첨부하여 보내시려면 잠시 후에 다시 시도해주십시오.",send_invalid_captcha_error:"잘못된 경로를 통해 메일 보내기를 시도하여 메일 발송이 되지 않았습니다.\n정상적인 경로로 메일을 다시 보내 주십시오.",
send_ndrive_attach_error:"네이버 클라우드 파일 첨부가 실패하였습니다.",send_smtp_error:"발송서버(SMTP) 접속 오류가 발생하였습니다.",send_error:"발송시 정의되지 않은 오류가 발생하였습니다.",
readreceipt_retreive_error:"메일을 회수하는데 실패하였습니다.",readreceipt_reserve_cancel_error:"예약/대기 발송을 취소하는데 실패하였습니다.\n상세 내역을 확인할 수 있는 수신확인 페이지로 이동하시겠습니까?",
calendar_make_error:"캘린더 정보를 생생하는데 실패하였습니다.",calendar_content_error:"캘린더 정보를 가져오는데 실패하였습니다.",calendar_reply_error:"캘린더 초대에 응답하는데 실패하였습니다.",
calender_wrong_parameter:"캘린더 파라미터가 일치 하지 않습니다.",address_group_list_error:"그룹 목록 오류입니다.",address_nhn_group_list_error:"사내 주소 그룹 목록 오류입니다.",
address_count_error:"주소록 갯수정보 오류입니다.",address_invalid_email_list:"이메일 목록이 유효하지 않습니다.",address_make_group_error:"주소록 그룹을 생성하지 못했습니다.",
address_set_frequent_group_error:"자주 사용하는 주소록/자주 사용하지 않는 주소록 설정이 실패하였습니다.",ndrive_file_upload_fail:"파일 업로드에 실패하였습니다.\n서비스 이용에 불편을 드려 대단히 죄송합니다.\n잠시 후 다시 시도해 주십시요.",
option_account_null:"계정 정보가 없습니다.",option_write_fromname_empty:"'보내는 사람' 내용을 입력 해 주세요.",option_write_fromname_add_error:"'보내는 사람' 추가에 실패하였습니다.",
option_write_fromname_wrong:"특수 문자 '<', '>', '\\', '\"'는 사용하실 수 없습니다.",option_write_fromname_overcount:"최대 저장 개수를 초과하였습니다.",
option_write_fromname_already_exist:"입력하신 이름이 이미 보내는 이름 목록에 있습니다.",option_smtp_only_for_individual:"개인 사용자에게만 지원되는 기능입니다.",
option_idomain_get_email_error:"개인도메인 이메일 정보를 가져오는데 실패하였습니다.",option_idomain_set_email_error:"개인도메인 이메일 정보를 설정하는데 실패하였습니다.",
option_folder_noname:"저장할 폴더 이름이 없습니다.",option_folder_duplicate:"저장할 메일함의 이름을 가진 메일함이 이미 존재합니다. 이메일함으로 사용하시겠습니까?",
reload:"페이지를 정상적으로 표시할 수 없습니다.\n'새로고침' 하시겠습니까?",not_defined_acp_error:"서버API 응답오류 : ",not_defined_method:"이 정의되어 있지 않습니다.",
not_handled_case:"미처리된 케이스.",write_no_content:"템플릿 오류입니다.",folder_not_exist:"메일함이 존재하지 않습니다.\n 받은메일함으로 이동합니다.",
search_index_error:"메일 검색 데이터를 업데이트 중에 있습니다. \n데이터 재생성 시 대략 10분 정도 소요될 수 있으므로 \n잠시 후 다시 검색해 주시기 바랍니다.",
option_pop3_account_fail:"가져올 외부계정의 POP3 설정이 잘못되었거나\n아이디 및 비밀번호가 잘못 입력된 경우\n외부메일 계정을 추가할 수 없습니다.\n정보를 확인하신 후 다시 시도해 주세요",
option_pop3_account_fail_max:"외부 메일 계정을 설정할 수 있는 횟수가 초과되었습니다. \n고객센터로 문의하여 주시기 바랍니다.",invalid_mail_form_desc:"메일주소 형식이 올바르지 않습니다.",
works_wrong_pass:"비밀번호가 맞지 않습니다. Works에 연동하여 사용한 네이버 id의 비밀번호를 입력해주세요.",works_wrong_configure:"소속된 Works에서 '외부 메일 가져오기'를 허용하지 않습니다. 관리자에게 문의하시길 바랍니다.",
works_exceed_10_pass:"기존 Works 메일 가져오기를 설정할 수 있는 횟수가 초과되었습니다. 고객센터로 문의하여 주시기 바랍니다.",pop3_works_common_fail:"알 수 없는 오류가 발생하였습니다. 잠시후 다시 시도하여 주세요.",
pop3_response_timeout:"선택한 외부 메일의 서버가 응답하지 않고 있습니다.\n잠시 후 다시 시도해주세요.",reserveMail_limit1:"발송 예약은 ",reserveMail_limit2:"통까지 설정 가능합니다. 수신확인 페이지에서 발송 예약 내역을 확인해 주세요.",
external_login_fail:"회사 외부에서 접속시에는 재로그인이 필요합니다. 로그인 페이지로 이동합니다.",no_login:"로그아웃 되었습니다.",no_security_download:"보안메일을 제외한 일반 메일만 저장됩니다.",
block_exe_file:"관리자가 제한한 파일 형식은 첨부할 수 없습니다.",block_exe_file_naver:"일부 실행 가능한 파일은 첨부할 수 없습니다.<br>",delete_exe_file:"첨부된 파일 중 일부 파일이 제거되었습니다.<br>일부 실행 가능한 파일은 첨부할 수 없습니다.<br>",
download_pc_block_title:"관리자가 제한하는 파일을 제외하고 다운로드 됩니다.",download_cloud_block_title:"관리자가 제한한 형식의 파일이 있습니다.",
download_block_subtitle:"관리자가 제한하는 파일은 다운로드할 수 없습니다.",preview_block_subtitle:"관리자가 제한하는 파일은 미리보기할 수 없습니다.",
upload_blocked_extension:"관리자가 제한한 파일형식",upload_blocked_extension_naver:"제한된 파일형식",help_upload_block_url:"https://help.worksmobile.com/contents/contents.nhn?serviceNo=2&categoryNo=1230",
help_download_block_url:"https://help.worksmobile.com/contents/contents.nhn?serviceNo=2&categoryNo=1231",
help_upload_block_url_naver:"https://help.naver.com/support/alias/mail/mail5.naver",virus_malware:"바이러스/악성코드",
virus_result:"진단명",unavailable_web_message:"메시지(PC웹)서비스는 IE10이상, Chrome, firefox에서 정상적으로 사용하실 수 있습니다.",
unavailable_date:"유효하지 않은 날짜입니다.",eoo:""},m:{del_unread:"안읽은 메일 삭제<i class='icon'></i>",del_unread_memo:"안읽은 메모 삭제<i class='icon'></i>",
read_all_unread:"안읽은 메일 모두 읽음 표시<i class='icon'></i>",read_all_unread_memo:"안읽은 메모 모두 읽음 표시<i class='icon'></i>",
list_no_split:"메일 목록만 보기",list_no_split_memo:"목록만 보기",all_mail:"모든 메일",all_memo:"모든 메모",menu_unread:"안 읽은 메일",
menu_unread_memo:"안 읽은 메모",mark_mail:"중요 메일",mark_memo:"중요 메모",attach_mail2:"첨부 메일",attach_memo2:"첨부 메모",
write_sending:"<img height='8' width='32' alt='' src='https://"+wm.staticDomain+"/static/pwe/nm/loading_white_160321.gif'><strong>메일</strong> 발송 중입니다.",
note_sending:"<img height='8' width='32' alt='' src='https://"+wm.staticDomain+"/static/pwe/nm/loading_white_160321.gif'>저장 중입니다.",
btn_write2:"메일쓰기",btn_write2_memo:"메모쓰기",btn_write2_tome:"내게쓰기",add_childfolder:"하위 메모함 추가",mailbox_modify:"메일함 수정",
mailbox_org_folder_name:"기존메일함 이름",mailbox_new_folder_name:"새메일함 이름",memobox_modify:"메모함 수정",memobox_org_folder_name:"기존메모함 이름",
memobox_new_folder_name:"새메모함 이름",new_folder:"새 메모함",no_folder:"메모함없음",rename_folder:"메모함 이름 수정",cannot_be_in_child_folder:"자신의 하위 메모함으로 이동할 수 없습니다.",
cannot_be_in_system_folder:"시스템 폴더 하위로는 메모함을 생성할 수 없습니다.",depth_limit_5:"메모함은 5depth 까지만 만드실 수 있습니다.",
count_limit_1000:"메모함 갯수는 1000개를 초과할 수 없습니다.",length_limit_20:"메모함 이름은 20자까지 입력이 가능합니다.",length_limit_70:"메모함 이름은 70자까지 입력이 가능합니다.",
noname:"메모함 이름을 입력하세요.",noname_save_folder:"저장할 메모함 이름을 넣어주십시오.",already_exist:"이미 존재하는 메모함입니다.",no_parent_folder:"상위 메모함이 존재하지 않아 메모함을 만드실 수 없습니다.",
slash_limit_position:"'/'는 메모함의 처음이나 마지막에 올수 없습니다.",nomail_to_backup:"백업할 메모가 없습니다.",fold_folder:"하위 메모함 열기/접기 토글",
clear_folder_type_trash:"{Name} 비우기 시, 메모함에 있던 모든 메모(중요메모 포함)는 휴지통으로 이동합니다.\n대량의 메모를 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n메모함을 비우시겠습니까?",
clear_folder_type_delete:"{Name} 를 비우시면, 메모함에 있던 모든 메모(중요메모 포함)는 삭제되며 복구할 수 없습니다.\n대량의 메모를 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n메모함을 비우시겠습니까?",
delete_folder_no_child_trash:"{Name} 삭제 시, 메모함에 있던 모든 메모(중요메모 포함)는 휴지통으로 이동합니다.\n대량의 메모를 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n메모함을 삭제하시겠습니까?",
delete_folder_no_child_delete:"{Name} 을 삭제하시면, 메모함에 있던 모든 메모(중요메모 포함)는 삭제되며 복구할 수 없습니다.\n대량의 메모를 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n메모함을 삭제하시겠습니까?",
delete_folder_has_child_trash:"{Name} 삭제 시, 하위 메모함도 함께 삭제되며\n하위 메모함을 포함하여 메모함에 있던 모든 메모(중요메모 포함)는 휴지통으로 이동합니다.\n대량의 메모를 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n메모함을 삭제하시겠습니까?",
delete_folder_has_child_delete:"{Name} 을 삭제하시면, 하위 메모함도 함께 삭제되며\n하위 메모함을 포함하여 메모함에 있던 모든 메모(중요메모 포함)가 삭제되어 복구할 수 없습니다.\n대량의 메모를 처리할 경우 시간이 오래 걸릴 수 있습니다.\n\n메모함을 삭제하시겠습니까?",
duplicate_folder_name:"같은 이름의 메모함이 이미 있습니다. 내 메모함 중 {FolderName} 메모함을 다른 이름으로 변경한 후에 이름 초기화를 해 주세요.",
confirm_delete_all:"현재 메모함에서 안읽은 메모(중요메모 포함)를 모두 삭제하시겠습니까?",folder_read_all:"메모함을 모두 읽음으로 표시하였습니다.",
read_all_folder:"{FolderName} 의 안 읽은 메모가 모두 읽음으로 표시됩니다.\n\n모두 읽음으로 표시하시겠습니까?",cannot_use_slash_foldername:"메모함 이름에 / 는 사용할 수 없습니다.",
nomemo:"메모함에 메모가 없습니다.",moved_mail_trash:"메모를 휴지통으로 이동했습니다.",moved_mail_trash_undo:"메모를 휴지통으로 이동했습니다. <a href='javascript:;' class='_c1(mlCore|cancelDeleteMoveMailFromNoti)'>실행취소</a>",
moved_mail_trash_undo_delete30:"메모를 휴지통으로 이동하며, 30일 보관 후 영구 삭제됩니다. <a href='javascript:;' class='_c1(mlCore|cancelDeleteMoveMailFromNoti)'>실행취소</a><a href='javascript:;' class='_c1(mlCore|optionConfirmFromNoti)'>설정확인</a>",
to_view_lang:"외국어 메모 보기",to_view_origin:"원문 보기",preview_mail:"메모 내용 미리보기",open_preview_mail_layer:"메모 내용 미리보기 레이어 열림",
view_popup:"새 창으로 메모 보기",popup_window:"새 창으로 메모 보기",delete_mark_mail:"중요 메모입니다.\n\n삭제하시겠습니까?",delete_include_mark_mail:"중요 메모 포함되어 있습니다.\n\n삭제하시겠습니까?",
no_prev_mail:"이전 메모가 없습니다.",no_next_mail:"다음 메모가 없습니다.",select_mail_num:"{sStatus}개의 메모를 선택했습니다.",mail:"메일",
memo:"메모",write_loading_mail:"<strong>메일 쓰기</strong> 로딩 중입니다.",write_loading_memo:"<strong>메모 쓰기</strong> 로딩 중입니다.",
read_mail:"읽은 메모",not_read_mail:"읽지않은 메모",remind_fail_setfail:"리마인드 설정에 실패하였습니다. 잠시후 다시 시도해주세요.",eoo:""
},ndrive:{virusMsg:"악성코드가 포함된 파일은 사용이 제한됩니다.",copyrightMsg:"저작권이 있는 음원, 동영상, 설치 파일은\n공유가 제한됩니다.",blockExtMsg:"관리자가 제한한 형식의 파일입니다.",
blockExtMsg_naver:"일부 실행 가능한 파일은 첨부할 수 없습니다.",eoo:""},eoo:""};